codex \
  --ask-for-approval never \
  exec --model gpt-5.3-codex \
  --local-provider none \
  --sandbox danger-full-access \
  -C /c/Users/me/work/ai/promptbook \
  <<'CODEX_PROMPT'

Implement user chat history

-   User is chatting with the agent. Store chats in some nice history.
-   This should be similar to other AI chatting platforms like ChatGPT, Claude, Gemini, etc. _(See screenshot for reference)_
-   User chats should be stored in a table `UserChat`
-   All of the messages in the chat should be stored as JSON in user chat.
-   Do not worry about editing messages in the past. The chat can be created, new, deleted, or continued, but it cannot be edited
-   Create database migration for the change
    -   Migrations are located in `/apps/agents-server/src/database/migrations`
    -   Be aware that table names in migrations have prefix `prefix_` _(look at existing migrations for reference)_
-   User chats are per agent per user. For each agent, user see different history of the chats because with one agent, a user can have a lot of chats, and with a different agent, a user can have none.
-   User can resume any of his chats at any time.
-   The chats are ordered by the time of the last message in the chat. So if the user has a chat with some agent, and then he continues this chat, this chat will be moved to the top of the list of chats.
-   When the user starts chat from the agent profile page (like https://praha13.ptbk.io/agents/qY7rrLbHFA1GCE/), it should always create a new chat, not continue with some old one.
-   Store current chat in the GET url parameter, for example https://praha13.ptbk.io/agents/qY7rrLbHFA1GCE/?chat=rTfQAdwsda, and when the user opens this url, it should open this chat.
    -   When the user opens the agent page without `?chat=...` parameter, it should open the most recent chat with this agent.
    -   This is not a sharing feature. This will be implemented later. The chat should be visible only for that one user, and if the user shares the link with someone else, this someone else should not see the chat because it is not their chat.
    -   Sharing will be implemented later.
    -   IDs of the chats should be generated by the same function as IDs of the agents.
-   This will work alongside the logging of the chat history _(table `ChatHistory`)_.
-   When the user is not logged in, the chat history are disabled
    -   But still, in other mechanisms (like logging chat history globally), it is working as it is working now. Do not change them in any way.
-   Keep in mind the DRY _(don't repeat yourself)_ principle.
-   This is a big change. Do a proper analysis of the project before you start implementing.
-   You are working with the [Agents Server](apps/agents-server)
-   Add the changes into the [changelog](changelog/_current-preversion.md)

![alt text](prompts/screenshots/2026-02-1230-agents-server-my-chats.png)
![alt text](prompts/screenshots/2026-02-1230-agents-server-my-chats-1.png)

**Common rules**

- Always analyze the context and requirements before generating any code.
- Keep in mind the DRY _(don't repeat yourself)_ principle.
- Write clear, maintainable, and well-documented code.
- Write JSDoc comments for all entities - functions, classes, types, top-level constants, etc.
    - When this entity is exported from the file and it is under `src` folder *(not for example in the `apps` folder)*, it must be marked either as `@public` or `@private` at the end of the JSDoc comment.
    - For example: "@private internal utility of <Chat/>" / "@public exported from `@promptbook/browser`"
    - If you dont know, prefer to mark it as private, we can always change it to public later, but changing from public to private may cause breaking changes.
- After code change, run the following tests to ensure everything works as expected:
    1) npm run test-name-discrepancies - tests that file names matches the exported names, for example if you export a class named "OpenAiAgent" from a file, the file should be named `OpenAiAgent.ts` *(not `ClaudeAgent.ts`)*. This helps to prevent typos and mismanagement of the project.
    2) npm run test-spellcheck - When using some new word, add it into the [dictionary](other/cspell-dictionaries)
    3) npm run test-lint - Linting
    4) npm run test-types - checks TypeScript types
    5) npm run test-package-generation - tests that build script is working correctly, also tests that all exported entities are correctly marked as public or private
    6) npm run test-unit - Unit tests
    7) npm run test-app-agents-server - Tests that the Agents Server app is working correctly
- you don't need to run every test, run them only when you make changes which may cause them to fail


**Additional context:**

- Attached images (if any) are relative to the root of the project.
-   **Promptbook Engine vs. Agent Server** sre two distinct parts you should know the difference:
    -   **Promptbook Engine** is the core engine that powers AI agents, it is located in `src` folder. It is framework-agnostic and can be used in different applications. It can run as standalone javascript/typescript library, CLI environment, or be integrated into different applications. It can be also runned in Agent Server:
    -   **Agent Server** is a specific application that uses the Promptbook Engine to provide a web and API interface for creating and interacting with AI agents. It is located in `apps/agents-server` folder.
-   **Commitments** are basic syntax elements that add specific functionalities to AI agents
    -   They are used in `agentSource`, there are commitments like `PERSONA`, `RULE`, `KNOWLEDGE`, `USE BROWSER`, `USE SEARCH ENGINE`, `META IMAGE`, etc.
    -   Commitments are in the folder `src/commitments`
    -   Each commitment starts with a keyword, e.g., `KNOWLEDGE`, `USE BROWSER`, etc. on a begining of the line and end by new co
    -   Agent source with commitments is parsed by two functions:
        -   `parseAgentSource` which is a lightweight parser for agent source, it parses basic information and its purpose is to be quick and synchronous. The commitments there are hardcoded.
        -   `createAgentModelRequirements` which is an asynchronous function that creates model requirements it applies each commitment one by one and works asynchronously.

CODEX_PROMPT