#!/usr/bin/env ts-node

import * as dotenv from 'dotenv';
dotenv.config({ path: '.env' });

import chalk from 'chalk';
import commander from 'commander';
import { readFile, writeFile } from 'fs/promises';
import glob from 'glob-promise';
import { normalizeTo_PascalCase } from 'n12';
import { join } from 'path';
import spaceTrim from 'spacetrim';
import { promptTemplatePipelineStringToJson } from '../../src/conversion/promptTemplatePipelineStringToJson';
import { string_name } from '../../src/types/typeAliases';
import { addAutoGeneratedSection } from '../../src/utils/markdown/addAutoGeneratedSection';
import { commit } from '../utils/autocommit/commit';
import { isWorkingTreeClean } from '../utils/autocommit/isWorkingTreeClean';

if (process.cwd() !== join(__dirname, '../..')) {
    console.error(chalk.red(`CWD must be root of the project`));
    process.exit(1);
}

const PTBK_SAMPLES_DIR = join(process.cwd(), 'samples/templates');

const program = new commander.Command();
program.option('--commit', `Autocommit changes`, false);
program.parse(process.argv);
const { commit: isCommited } = program.opts();

generateSampleGraphs({ isCommited })
    .catch((error) => {
        console.error(chalk.bgRed(error.name));
        console.error(error);
        process.exit(1);
    })
    .then(() => {
        process.exit(0);
    });

async function generateSampleGraphs({ isCommited }: { isCommited: boolean }) {
    console.info(`🏭📖  Generate samples mermaid graphs -> .ptbk.md`);

    if (isCommited && !(await isWorkingTreeClean(process.cwd()))) {
        throw new Error(`Working tree is not clean`);
    }

    for (const ptbkMarkdownFilePath of await glob(join(PTBK_SAMPLES_DIR, '*.ptbk.md').split('\\').join('/'))) {
        console.info(`📖  Generating mermaid graph in ${ptbkMarkdownFilePath}`);
        let ptbkMarkdown = await readFile(ptbkMarkdownFilePath, 'utf-8');

        try {
            // eslint-disable-next-line @typescript-eslint/no-explicit-any
            const ptbkJson = promptTemplatePipelineStringToJson(ptbkMarkdown as any /* <- TODO: Remove any */);

            const parameterNameToTemplateName = (parameterName: string_name) => {
                const parameter = ptbkJson.parameters.find((parameter) => parameter.name === parameterName);

                if (!parameter) {
                    throw new Error(`Could not find {${parameterName}}`);
                    //              <- TODO: [🥨] Make some NeverShouldHappenError
                }

                if (parameter.isInput) {
                    return 'input';
                }

                const template = ptbkJson.promptTemplates.find(
                    (template) => template.resultingParameterName === parameterName,
                );

                if (!template) {
                    throw new Error(`Could not find template for {${parameterName}}`);
                }

                return 'template' + normalizeTo_PascalCase(template.title);
            };

            const ptbkMermaid = spaceTrim(
                (block) => `

                    %% 🔮 Tip: Open this on GitHub or in the VSCode website to see the Mermaid graph visually

                    flowchart LR
                      subgraph "${ptbkJson.title}"

                          direction TB

                          input[Input]:::hidden
                          ${block(
                              ptbkJson.promptTemplates
                                  .flatMap(({ title, dependentParameterNames, resultingParameterName }) => [
                                      `${parameterNameToTemplateName(resultingParameterName)}[${title}]`,
                                      ...dependentParameterNames.map(
                                          (dependentParameterName) =>
                                              `${parameterNameToTemplateName(
                                                  dependentParameterName,
                                              )}--"{${dependentParameterName}}"-->${parameterNameToTemplateName(
                                                  resultingParameterName,
                                              )}`,
                                      ),
                                  ])
                                  .join('\n'),
                          )}

                          classDef hidden display: none;

                      end;



            `,
            );

            const ptbkMermaidBlock = spaceTrim(
                (block) => `
                \`\`\`mermaid
                ${block(ptbkMermaid)}
                \`\`\`
            `,
            );

            ptbkMarkdown = addAutoGeneratedSection(ptbkMarkdown, {
                sectionName: 'Graph',
                sectionContent: ptbkMermaidBlock,
            });

            await writeFile(ptbkMarkdownFilePath, ptbkMarkdown);
        } catch (error) {
            if (!(error instanceof Error)) {
                throw error;
            }

            console.info(chalk.bgGray('========================='));
            console.info(chalk.red(`Error in ${ptbkMarkdownFilePath}`));
            console.error(chalk.bgRed(error.name));
            console.error(error);
            console.info(chalk.bgGray('========================='));
        }
    }

    if (isCommited) {
        await commit(PTBK_SAMPLES_DIR, `📖 Generate samples mermaid graphs -> .ptbk.md`);
    }

    console.info(`[ Done 📖  Generate samples mermaid graphs -> .ptbk.md]`);
}

/**
 * TODO: Maybe use some Mermaid library instead of string templating
 */
