# [🐋] docker-compose.yml
services:
    promptbook:
        build: .
        image: hejny/promptbook:latest
        ports:
            - 4440:4440
        # TODO: [🧠][🐋] Make volume for `.promptbook` folder
        # volumes:
        #     - ./logs:/opt/chutoo/promptbook-module/
        env_file: '.env'
        # <- TODO: Is this secure, isn't there some way how env variables leaks into DockerHub?
# TODO: [🚑] This file should be in `/src/packages/docker/...`
