CREATE TABLE IF NOT EXISTS "prefix_GenerationLock" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
    "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
    "lockKey" TEXT NOT NULL,
    "expiresAt" TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE UNIQUE INDEX IF NOT EXISTS "prefix_GenerationLock_lockKey_idx" ON "prefix_GenerationLock" ("lockKey");

ALTER TABLE "prefix_GenerationLock" ENABLE ROW LEVEL SECURITY;

COMMENT ON TABLE "prefix_GenerationLock" IS 'Locks to prevent concurrent expensive operations like image generation';
COMMENT ON COLUMN "prefix_GenerationLock"."lockKey" IS 'Unique key for the lock (e.g. agent-avatar-<hash>)';
COMMENT ON COLUMN "prefix_GenerationLock"."expiresAt" IS 'When the lock expires and can be overridden';
