
-- Table: Message
CREATE TABLE IF NOT EXISTS "prefix_Message" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
    "channel" TEXT NOT NULL,
    "direction" TEXT NOT NULL,
    "sender" JSONB NOT NULL,
    "recipients" JSONB,
    "content" TEXT NOT NULL,
    "threadId" TEXT,
    "metadata" JSONB
);

COMMENT ON TABLE "prefix_Message" IS 'A generic message structure for various communication channels';
COMMENT ON COLUMN "prefix_Message"."channel" IS 'The communication channel of the message (e.g. EMAIL, PROMPTBOOK_CHAT)';
COMMENT ON COLUMN "prefix_Message"."direction" IS 'Is the message send from the Promptbook or to the Promptbook';
COMMENT ON COLUMN "prefix_Message"."sender" IS 'Who sent the message';
COMMENT ON COLUMN "prefix_Message"."recipients" IS 'Who are the recipients of the message';
COMMENT ON COLUMN "prefix_Message"."content" IS 'The content of the message as markdown';
COMMENT ON COLUMN "prefix_Message"."threadId" IS 'The thread identifier the message belongs to';


-- Table: MessageSendAttempt
CREATE TABLE IF NOT EXISTS "prefix_MessageSendAttempt" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
    
    "messageId" BIGINT NOT NULL REFERENCES "prefix_Message"("id") ON DELETE CASCADE,
    "providerName" TEXT NOT NULL,
    "isSuccessful" BOOLEAN NOT NULL,
    "raw" JSONB
);

COMMENT ON TABLE "prefix_MessageSendAttempt" IS 'Stores each attempt to send the message';
COMMENT ON COLUMN "prefix_MessageSendAttempt"."messageId" IS 'The message that was attempted to be sent';
COMMENT ON COLUMN "prefix_MessageSendAttempt"."providerName" IS 'The name of the provider used for sending';
COMMENT ON COLUMN "prefix_MessageSendAttempt"."isSuccessful" IS 'Whether the attempt was successful';
COMMENT ON COLUMN "prefix_MessageSendAttempt"."raw" IS 'Raw response or error from the provider';

ALTER TABLE "prefix_Message" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "prefix_MessageSendAttempt" ENABLE ROW LEVEL SECURITY;
