CREATE TABLE IF NOT EXISTS "prefix_File" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
    
    "userId" BIGINT REFERENCES "prefix_User"("id"),
    "fileName" TEXT NOT NULL,
    "fileSize" BIGINT NOT NULL,
    "fileType" TEXT NOT NULL,
    "cdnUrl" TEXT NOT NULL,
    "purpose" TEXT NOT NULL
);

ALTER TABLE "prefix_File" ENABLE ROW LEVEL SECURITY;

COMMENT ON COLUMN "prefix_File"."userId" IS 'Reference to the user who uploaded the file';
COMMENT ON COLUMN "prefix_File"."fileName" IS 'Original name of the uploaded file';
COMMENT ON COLUMN "prefix_File"."fileSize" IS 'Size of the file in bytes';
COMMENT ON COLUMN "prefix_File"."fileType" IS 'MIME type of the file';
COMMENT ON COLUMN "prefix_File"."cdnUrl" IS 'Public URL of the file in CDN';
COMMENT ON COLUMN "prefix_File"."purpose" IS 'Purpose of the upload (e.g. KNOWLEDGE, SERVER_FAVICON_URL)';
