-- Note: This is primary source of truth for the database schema
--       In future we want to be compatible with more then Supabase so we keep SQL as main schema definition
--       To update, search for [💽]


CREATE TABLE IF NOT EXISTS "prefix_Metadata" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
    "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
    "key" TEXT NOT NULL,
    "value" TEXT NOT NULL,
    "note" TEXT NULL,
    CONSTRAINT "prefix_Metadata_key_key" UNIQUE ("key")
);

ALTER TABLE "prefix_Metadata" ENABLE ROW LEVEL SECURITY;
