CREATE TABLE IF NOT EXISTS "prefix_KnowledgeIndexSnapshot" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
    "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),

    "agentPermanentId" TEXT NOT NULL,
    "knowledgeHash" TEXT NOT NULL,
    "knowledgeSources" JSONB NOT NULL DEFAULT '[]'::jsonb,
    "documentCount" INTEGER NOT NULL DEFAULT 0,
    "documentStore" JSONB NULL,
    "indexStore" JSONB NULL,
    "vectorStore" JSONB NULL
);

CREATE UNIQUE INDEX IF NOT EXISTS "prefix_KnowledgeIndexSnapshot_agentPermanentId_idx"
    ON "prefix_KnowledgeIndexSnapshot" ("agentPermanentId");

CREATE INDEX IF NOT EXISTS "prefix_KnowledgeIndexSnapshot_knowledgeHash_idx"
    ON "prefix_KnowledgeIndexSnapshot" ("knowledgeHash");

ALTER TABLE "prefix_KnowledgeIndexSnapshot"
    DROP CONSTRAINT IF EXISTS "prefix_KnowledgeIndexSnapshot_agentPermanentId_fkey",
    ADD CONSTRAINT "prefix_KnowledgeIndexSnapshot_agentPermanentId_fkey"
    FOREIGN KEY ("agentPermanentId")
    REFERENCES "prefix_Agent"("permanentId")
    ON DELETE CASCADE;

ALTER TABLE "prefix_KnowledgeIndexSnapshot" ENABLE ROW LEVEL SECURITY;
