DO $$
BEGIN
    CREATE TYPE "_ServerEnvironment" AS ENUM ('PRODUCTION', 'PREVIEW');
EXCEPTION
    WHEN duplicate_object THEN NULL;
END
$$;

CREATE TABLE IF NOT EXISTS "_Server" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "name" TEXT NOT NULL,
    "environment" "_ServerEnvironment" NOT NULL,
    "domain" TEXT NOT NULL,
    "tablePrefix" TEXT NOT NULL,
    "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
    "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()
);

CREATE UNIQUE INDEX IF NOT EXISTS "_Server_name_key" ON "_Server" ("name");
CREATE UNIQUE INDEX IF NOT EXISTS "_Server_domain_key" ON "_Server" ("domain");
CREATE UNIQUE INDEX IF NOT EXISTS "_Server_tablePrefix_key" ON "_Server" ("tablePrefix");

ALTER TABLE "_Server" ENABLE ROW LEVEL SECURITY;
