CREATE TABLE IF NOT EXISTS "prefix_UserWallet" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
    "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
    "userId" BIGINT NOT NULL,
    "agentPermanentId" TEXT NULL,
    "recordType" TEXT NOT NULL,
    "service" TEXT NOT NULL,
    "key" TEXT NOT NULL DEFAULT 'default',
    "username" TEXT NULL,
    "password" TEXT NULL,
    "secret" TEXT NULL,
    "cookies" TEXT NULL,
    "isGlobal" BOOLEAN NOT NULL DEFAULT FALSE,
    "deletedAt" TIMESTAMP WITH TIME ZONE NULL,
    CONSTRAINT "prefix_UserWallet_userId_fkey"
        FOREIGN KEY ("userId")
        REFERENCES "prefix_User"("id")
        ON DELETE CASCADE,
    CONSTRAINT "prefix_UserWallet_agentPermanentId_fkey"
        FOREIGN KEY ("agentPermanentId")
        REFERENCES "prefix_Agent"("permanentId")
        ON DELETE CASCADE,
    CONSTRAINT "prefix_UserWallet_scope_check"
        CHECK (
            ("isGlobal" = TRUE AND "agentPermanentId" IS NULL) OR
            ("isGlobal" = FALSE AND "agentPermanentId" IS NOT NULL)
        ),
    CONSTRAINT "prefix_UserWallet_recordType_check"
        CHECK ("recordType" IN ('USERNAME_PASSWORD', 'SESSION_COOKIE', 'ACCESS_TOKEN'))
);

CREATE INDEX IF NOT EXISTS "prefix_UserWallet_userId_idx"
    ON "prefix_UserWallet" ("userId");

CREATE INDEX IF NOT EXISTS "prefix_UserWallet_userId_agentPermanentId_idx"
    ON "prefix_UserWallet" ("userId", "agentPermanentId");

CREATE INDEX IF NOT EXISTS "prefix_UserWallet_userId_isGlobal_idx"
    ON "prefix_UserWallet" ("userId", "isGlobal");

CREATE INDEX IF NOT EXISTS "prefix_UserWallet_lookup_idx"
    ON "prefix_UserWallet" ("userId", "recordType", "service", "key");

CREATE INDEX IF NOT EXISTS "prefix_UserWallet_deletedAt_idx"
    ON "prefix_UserWallet" ("deletedAt");
