CREATE TABLE IF NOT EXISTS "prefix_AgentAvatarParameters" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
    "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),

    "version" TEXT NOT NULL,
    "agentFingerprint" TEXT NOT NULL,
    "agentPermanentId" TEXT NULL,
    "agentName" TEXT NOT NULL,
    "parameters" JSONB NOT NULL
);

CREATE UNIQUE INDEX IF NOT EXISTS "prefix_AgentAvatarParameters_version_hash_idx"
    ON "prefix_AgentAvatarParameters" ("version", "agentFingerprint");

CREATE INDEX IF NOT EXISTS "prefix_AgentAvatarParameters_agentPermanentId_idx"
    ON "prefix_AgentAvatarParameters" ("agentPermanentId");

ALTER TABLE "prefix_AgentAvatarParameters" ENABLE ROW LEVEL SECURITY;

COMMENT ON TABLE "prefix_AgentAvatarParameters" IS 'Stored intermediate default-avatar parameters for one deterministic renderer version and agent fingerprint.';
COMMENT ON COLUMN "prefix_AgentAvatarParameters"."version" IS 'Shared schema/render version for deterministic default avatars.';
COMMENT ON COLUMN "prefix_AgentAvatarParameters"."agentFingerprint" IS 'Stable fingerprint of the canonical agent source used to key stage-1 avatar parameters.';
COMMENT ON COLUMN "prefix_AgentAvatarParameters"."agentPermanentId" IS 'Optional stable agent identifier used for lookup and maintenance.';
COMMENT ON COLUMN "prefix_AgentAvatarParameters"."agentName" IS 'Human-readable agent name at the time the avatar parameters were stored.';
COMMENT ON COLUMN "prefix_AgentAvatarParameters"."parameters" IS 'Structured JSON payload produced by stage 1 and consumed by the deterministic stage-2 renderer.';
