ALTER TABLE "prefix_User"
    ADD COLUMN IF NOT EXISTS "email" TEXT NULL,
    ADD COLUMN IF NOT EXISTS "displayName" TEXT NULL,
    ADD COLUMN IF NOT EXISTS "authenticationProvider" TEXT NOT NULL DEFAULT 'LOCAL';

COMMENT ON COLUMN "prefix_User"."email" IS 'Email address used for external authentication providers such as Shibboleth.';
COMMENT ON COLUMN "prefix_User"."displayName" IS 'Human-readable display name from external authentication providers.';
COMMENT ON COLUMN "prefix_User"."authenticationProvider" IS 'Primary authentication provider marker. Values include LOCAL, SHIBBOLETH, and LOCAL_AND_SHIBBOLETH.';

CREATE TABLE IF NOT EXISTS "prefix_ShibbolethUserIdentity" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
    "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
    "userId" BIGINT NOT NULL,
    "email" TEXT NOT NULL,
    "displayName" TEXT NULL,
    "nameId" TEXT NULL,
    "nameIdFormat" TEXT NULL,
    "unstructuredName" TEXT NULL,
    "eduPersonPrincipalName" TEXT NULL,
    "rawAttributes" JSONB NULL,
    "lastLoggedInAt" TIMESTAMP WITH TIME ZONE NULL,
    "loginCount" BIGINT NOT NULL DEFAULT 0
);

COMMENT ON TABLE "prefix_ShibbolethUserIdentity" IS 'Link between Agents Server users and Shibboleth identities.';
COMMENT ON COLUMN "prefix_ShibbolethUserIdentity"."rawAttributes" IS 'Raw SAML assertion profile attributes received from Shibboleth.';

CREATE UNIQUE INDEX IF NOT EXISTS "prefix_ShibbolethUserIdentity_userId_idx"
    ON "prefix_ShibbolethUserIdentity" ("userId");
CREATE UNIQUE INDEX IF NOT EXISTS "prefix_ShibbolethUserIdentity_email_idx"
    ON "prefix_ShibbolethUserIdentity" ("email");
CREATE UNIQUE INDEX IF NOT EXISTS "prefix_ShibbolethUserIdentity_nameId_idx"
    ON "prefix_ShibbolethUserIdentity" ("nameId");
CREATE INDEX IF NOT EXISTS "prefix_ShibbolethUserIdentity_lastLoggedInAt_idx"
    ON "prefix_ShibbolethUserIdentity" ("lastLoggedInAt" DESC);

ALTER TABLE "prefix_ShibbolethUserIdentity"
    DROP CONSTRAINT IF EXISTS "prefix_ShibbolethUserIdentity_userId_fkey",
    ADD CONSTRAINT "prefix_ShibbolethUserIdentity_userId_fkey"
    FOREIGN KEY ("userId")
    REFERENCES "prefix_User"("id")
    ON DELETE CASCADE;

ALTER TABLE "prefix_ShibbolethUserIdentity" ENABLE ROW LEVEL SECURITY;

CREATE TABLE IF NOT EXISTS "prefix_ShibbolethAuthenticationAttempt" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
    "stage" TEXT NOT NULL,
    "status" TEXT NOT NULL,
    "userId" BIGINT NULL,
    "email" TEXT NULL,
    "displayName" TEXT NULL,
    "nameId" TEXT NULL,
    "relayState" TEXT NULL,
    "ip" TEXT NULL,
    "userAgent" TEXT NULL,
    "errorMessage" TEXT NULL,
    "rawAttributes" JSONB NULL
);

COMMENT ON TABLE "prefix_ShibbolethAuthenticationAttempt" IS 'Audit log of Shibboleth authentication attempts.';
COMMENT ON COLUMN "prefix_ShibbolethAuthenticationAttempt"."stage" IS 'Authentication process stage such as LOGIN_REQUEST or ASSERTION_CONSUMER_SERVICE.';
COMMENT ON COLUMN "prefix_ShibbolethAuthenticationAttempt"."status" IS 'Attempt result such as STARTED, REDIRECTED, SUCCESS, FAILED, or REJECTED.';
COMMENT ON COLUMN "prefix_ShibbolethAuthenticationAttempt"."rawAttributes" IS 'Raw SAML assertion profile attributes when available.';

CREATE INDEX IF NOT EXISTS "prefix_ShibbolethAuthenticationAttempt_createdAt_idx"
    ON "prefix_ShibbolethAuthenticationAttempt" ("createdAt" DESC);
CREATE INDEX IF NOT EXISTS "prefix_ShibbolethAuthenticationAttempt_email_idx"
    ON "prefix_ShibbolethAuthenticationAttempt" ("email");

ALTER TABLE "prefix_ShibbolethAuthenticationAttempt"
    DROP CONSTRAINT IF EXISTS "prefix_ShibbolethAuthenticationAttempt_userId_fkey",
    ADD CONSTRAINT "prefix_ShibbolethAuthenticationAttempt_userId_fkey"
    FOREIGN KEY ("userId")
    REFERENCES "prefix_User"("id")
    ON DELETE SET NULL;

ALTER TABLE "prefix_ShibbolethAuthenticationAttempt" ENABLE ROW LEVEL SECURITY;

INSERT INTO "prefix_Metadata" ("key", "value", "note", "createdAt", "updatedAt")
SELECT 'IS_SHIBBOLETH_AUTH_ACTIVE',
       'false',
       'Enable Shibboleth authentication alongside standard username/password login.',
       NOW(),
       NOW()
WHERE NOT EXISTS (SELECT 1 FROM "prefix_Metadata" WHERE "key" = 'IS_SHIBBOLETH_AUTH_ACTIVE');

INSERT INTO "prefix_Metadata" ("key", "value", "note", "createdAt", "updatedAt")
SELECT 'SHIBBOLETH_IDP_METADATA_URL',
       '',
       'URL of the Shibboleth Identity Provider metadata XML. For Silesian University this is https://idp-cro.slu.cz/idp/shibboleth.',
       NOW(),
       NOW()
WHERE NOT EXISTS (SELECT 1 FROM "prefix_Metadata" WHERE "key" = 'SHIBBOLETH_IDP_METADATA_URL');

INSERT INTO "prefix_Metadata" ("key", "value", "note", "createdAt", "updatedAt")
SELECT 'SHIBBOLETH_IDP_METADATA_XML',
       '',
       'Optional pasted Shibboleth Identity Provider metadata XML. Used instead of SHIBBOLETH_IDP_METADATA_URL when filled.',
       NOW(),
       NOW()
WHERE NOT EXISTS (SELECT 1 FROM "prefix_Metadata" WHERE "key" = 'SHIBBOLETH_IDP_METADATA_XML');

INSERT INTO "prefix_Metadata" ("key", "value", "note", "createdAt", "updatedAt")
SELECT 'SHIBBOLETH_SP_ENTITY_ID',
       '',
       'Optional Service Provider entity ID override. When empty, Agents Server uses the generated Shibboleth metadata endpoint URL.',
       NOW(),
       NOW()
WHERE NOT EXISTS (SELECT 1 FROM "prefix_Metadata" WHERE "key" = 'SHIBBOLETH_SP_ENTITY_ID');

INSERT INTO "prefix_Metadata" ("key", "value", "note", "createdAt", "updatedAt")
SELECT 'SHIBBOLETH_EMAIL_ATTRIBUTE_NAMES',
       'mail email urn:oid:0.9.2342.19200300.100.1.3',
       'Space-separated SAML attribute names accepted as the user email during Shibboleth login.',
       NOW(),
       NOW()
WHERE NOT EXISTS (SELECT 1 FROM "prefix_Metadata" WHERE "key" = 'SHIBBOLETH_EMAIL_ATTRIBUTE_NAMES');

INSERT INTO "prefix_Metadata" ("key", "value", "note", "createdAt", "updatedAt")
SELECT 'SHIBBOLETH_DISPLAY_NAME_ATTRIBUTE_NAMES',
       'displayName urn:oid:2.16.840.1.113730.3.1.241',
       'Space-separated SAML attribute names accepted as the user display name during Shibboleth login.',
       NOW(),
       NOW()
WHERE NOT EXISTS (SELECT 1 FROM "prefix_Metadata" WHERE "key" = 'SHIBBOLETH_DISPLAY_NAME_ATTRIBUTE_NAMES');

INSERT INTO "prefix_Metadata" ("key", "value", "note", "createdAt", "updatedAt")
SELECT 'SHIBBOLETH_UNSTRUCTURED_NAME_ATTRIBUTE_NAMES',
       'unstructuredName eduPersonPrincipalName urn:oid:1.3.6.1.4.1.5923.1.1.1.6 uid',
       'Space-separated SAML attribute names accepted as the institutional identifier during Shibboleth login.',
       NOW(),
       NOW()
WHERE NOT EXISTS (SELECT 1 FROM "prefix_Metadata" WHERE "key" = 'SHIBBOLETH_UNSTRUCTURED_NAME_ATTRIBUTE_NAMES');
