CREATE TABLE  prefix_UserMemory (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    createdAt TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT timezone('utc'::text, now()),
    updatedAt TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT timezone('utc'::text, now()),
    userId BIGINT NOT NULL,
    agentId BIGINT NULL,
    agentName TEXT NULL,
    agentPermanentId TEXT NULL,
    title TEXT NOT NULL,
    content TEXT NOT NULL,
    isGlobal BOOLEAN NOT NULL DEFAULT FALSE,
    FOREIGN KEY (userId) REFERENCES prefix_User(id) ON DELETE CASCADE,
    FOREIGN KEY (agentId) REFERENCES prefix_Agent(id) ON DELETE CASCADE
);

CREATE INDEX prefix_UserMemory_userId_idx ON prefix_UserMemory (userId);
CREATE INDEX prefix_UserMemory_agentId_idx ON prefix_UserMemory (agentId);
