CREATE TABLE IF NOT EXISTS "prefix_AgentPreparation" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
    "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),

    "agentPermanentId" TEXT NOT NULL,
    "targetFingerprint" TEXT NOT NULL,
    "lastPreparedFingerprint" TEXT NULL,
    "status" TEXT NOT NULL DEFAULT 'SCHEDULED',
    "triggerReason" TEXT NOT NULL,
    "scheduledAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
    "runAfter" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
    "startedAt" TIMESTAMP WITH TIME ZONE NULL,
    "completedAt" TIMESTAMP WITH TIME ZONE NULL,
    "failedAt" TIMESTAMP WITH TIME ZONE NULL,
    "retryCount" INTEGER NOT NULL DEFAULT 0,
    "lastError" TEXT NULL,
    "lastDurationMs" INTEGER NULL
);

CREATE UNIQUE INDEX IF NOT EXISTS "prefix_AgentPreparation_agentPermanentId_idx"
    ON "prefix_AgentPreparation" ("agentPermanentId");

CREATE INDEX IF NOT EXISTS "prefix_AgentPreparation_status_runAfter_idx"
    ON "prefix_AgentPreparation" ("status", "runAfter");

ALTER TABLE "prefix_AgentPreparation"
    DROP CONSTRAINT IF EXISTS "prefix_AgentPreparation_agentPermanentId_fkey",
    ADD CONSTRAINT "prefix_AgentPreparation_agentPermanentId_fkey"
    FOREIGN KEY ("agentPermanentId")
    REFERENCES "prefix_Agent"("permanentId")
    ON DELETE CASCADE;

ALTER TABLE "prefix_AgentPreparation" ENABLE ROW LEVEL SECURITY;
