
CREATE TABLE IF NOT EXISTS "prefix_AgentFolder" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "name" TEXT NOT NULL,
    "parentId" BIGINT NULL,
    "sortOrder" BIGINT NOT NULL DEFAULT CAST(EXTRACT(EPOCH FROM now()) * 1000 AS BIGINT),
    "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
    "updatedAt" TIMESTAMP WITH TIME ZONE NULL DEFAULT NULL,
    "deletedAt" TIMESTAMP WITH TIME ZONE NULL DEFAULT NULL
);

CREATE INDEX IF NOT EXISTS "prefix_AgentFolder_parentId_idx" ON "prefix_AgentFolder" ("parentId");
CREATE INDEX IF NOT EXISTS "prefix_AgentFolder_sortOrder_idx" ON "prefix_AgentFolder" ("sortOrder");
CREATE UNIQUE INDEX IF NOT EXISTS "prefix_AgentFolder_parent_name_key"
    ON "prefix_AgentFolder" (COALESCE("parentId", 0), "name")
    WHERE "deletedAt" IS NULL;

ALTER TABLE "prefix_AgentFolder" ENABLE ROW LEVEL SECURITY;

ALTER TABLE "prefix_AgentFolder"
    DROP CONSTRAINT IF EXISTS "prefix_AgentFolder_parentId_fkey",
    ADD CONSTRAINT "prefix_AgentFolder_parentId_fkey"
    FOREIGN KEY ("parentId")
    REFERENCES "prefix_AgentFolder"("id")
    ON DELETE SET NULL;

ALTER TABLE "prefix_Agent" ADD COLUMN IF NOT EXISTS "folderId" BIGINT NULL;
ALTER TABLE "prefix_Agent" ADD COLUMN IF NOT EXISTS "sortOrder" BIGINT NOT NULL DEFAULT CAST(EXTRACT(EPOCH FROM now()) * 1000 AS BIGINT);

CREATE INDEX IF NOT EXISTS "prefix_Agent_folderId_idx" ON "prefix_Agent" ("folderId");
CREATE INDEX IF NOT EXISTS "prefix_Agent_sortOrder_idx" ON "prefix_Agent" ("sortOrder");

ALTER TABLE "prefix_Agent"
    DROP CONSTRAINT IF EXISTS "prefix_Agent_folderId_fkey",
    ADD CONSTRAINT "prefix_Agent_folderId_fkey"
    FOREIGN KEY ("folderId")
    REFERENCES "prefix_AgentFolder"("id")
    ON DELETE SET NULL;

UPDATE "prefix_Agent"
SET "sortOrder" = "id"
WHERE "sortOrder" IS NULL OR "sortOrder" = 0;
