CREATE TABLE IF NOT EXISTS "prefix_AgentExternals" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
    "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),

    "type" TEXT NOT NULL,
    "hash" TEXT NOT NULL,
    "externalId" TEXT NOT NULL
);

CREATE UNIQUE INDEX IF NOT EXISTS "prefix_AgentExternals_type_hash_idx" ON "prefix_AgentExternals" ("type", "hash");

ALTER TABLE "prefix_AgentExternals" ENABLE ROW LEVEL SECURITY;

ALTER TABLE "prefix_Agent" DROP COLUMN IF EXISTS "preparedExternals";
