CREATE TABLE IF NOT EXISTS "prefix_UserMemory" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
    "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
    "userId" BIGINT NOT NULL,
    "agentPermanentId" TEXT NULL,
    "content" TEXT NOT NULL,
    "isGlobal" BOOLEAN NOT NULL DEFAULT FALSE,
    CONSTRAINT "prefix_UserMemory_userId_fkey"
        FOREIGN KEY ("userId")
        REFERENCES "prefix_User"("id")
        ON DELETE CASCADE,
    CONSTRAINT "prefix_UserMemory_agentPermanentId_fkey"
        FOREIGN KEY ("agentPermanentId")
        REFERENCES "prefix_Agent"("permanentId")
        ON DELETE CASCADE,
    CONSTRAINT "prefix_UserMemory_scope_check"
        CHECK (
            ("isGlobal" = TRUE AND "agentPermanentId" IS NULL) OR
            ("isGlobal" = FALSE AND "agentPermanentId" IS NOT NULL)
        )
);

CREATE INDEX IF NOT EXISTS "prefix_UserMemory_userId_idx" ON "prefix_UserMemory" ("userId");
CREATE INDEX IF NOT EXISTS "prefix_UserMemory_userId_agentPermanentId_idx" ON "prefix_UserMemory" ("userId", "agentPermanentId");
CREATE INDEX IF NOT EXISTS "prefix_UserMemory_userId_isGlobal_idx" ON "prefix_UserMemory" ("userId", "isGlobal");

