CREATE TABLE IF NOT EXISTS "prefix_AgentDefaultAvatar" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
    "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),

    "agentPermanentId" TEXT NULL,
    "agentFingerprint" TEXT NOT NULL,
    "sourceHash" TEXT NOT NULL,
    "schemaVersion" TEXT NOT NULL,
    "renderVersion" TEXT NOT NULL,
    "parameters" JSONB NOT NULL
);

CREATE UNIQUE INDEX IF NOT EXISTS "prefix_AgentDefaultAvatar_agentFingerprint_idx"
    ON "prefix_AgentDefaultAvatar" ("agentFingerprint");

CREATE INDEX IF NOT EXISTS "prefix_AgentDefaultAvatar_agentPermanentId_idx"
    ON "prefix_AgentDefaultAvatar" ("agentPermanentId");

ALTER TABLE "prefix_AgentDefaultAvatar"
    DROP CONSTRAINT IF EXISTS "prefix_AgentDefaultAvatar_agentPermanentId_fkey",
    ADD CONSTRAINT "prefix_AgentDefaultAvatar_agentPermanentId_fkey"
    FOREIGN KEY ("agentPermanentId")
    REFERENCES "prefix_Agent"("permanentId")
    ON DELETE SET NULL;

ALTER TABLE "prefix_AgentDefaultAvatar" ENABLE ROW LEVEL SECURITY;

COMMENT ON TABLE "prefix_AgentDefaultAvatar" IS 'Stage-1 cache of deterministic procedural default-avatar parameters derived from an agent book/profile.';
COMMENT ON COLUMN "prefix_AgentDefaultAvatar"."agentPermanentId" IS 'Optional permanent agent id for bookkeeping and cache inspection.';
COMMENT ON COLUMN "prefix_AgentDefaultAvatar"."agentFingerprint" IS 'Stable cache key derived from the resolved source hash plus avatar schema/render versions.';
COMMENT ON COLUMN "prefix_AgentDefaultAvatar"."sourceHash" IS 'Stable hash of the resolved agent source used to invalidate cached avatar parameters when the book changes.';
COMMENT ON COLUMN "prefix_AgentDefaultAvatar"."schemaVersion" IS 'Version of the stored deterministic-avatar parameter schema.';
COMMENT ON COLUMN "prefix_AgentDefaultAvatar"."renderVersion" IS 'Version of the deterministic pixel-art renderer expected by the stored parameters.';
COMMENT ON COLUMN "prefix_AgentDefaultAvatar"."parameters" IS 'Structured JSON parameters reused to render the deterministic procedural avatar still image.';
