CREATE TABLE IF NOT EXISTS "prefix_DefaultFederatedAgent" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
    "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
    "normalizedName" TEXT NOT NULL,
    "sourceServerUrl" TEXT NOT NULL,
    "sourceAgentIdentifier" TEXT NOT NULL,
    "localPermanentId" TEXT NULL,
    CONSTRAINT "prefix_DefaultFederatedAgent_normalizedName_key" UNIQUE ("normalizedName"),
    CONSTRAINT "prefix_DefaultFederatedAgent_localPermanentId_fkey"
        FOREIGN KEY ("localPermanentId")
        REFERENCES "prefix_Agent" ("permanentId")
        ON DELETE SET NULL
);

CREATE INDEX IF NOT EXISTS "prefix_DefaultFederatedAgent_localPermanentId_idx"
    ON "prefix_DefaultFederatedAgent" ("localPermanentId");

CREATE INDEX IF NOT EXISTS "prefix_DefaultFederatedAgent_sourceServerUrl_idx"
    ON "prefix_DefaultFederatedAgent" ("sourceServerUrl");
