CREATE TABLE IF NOT EXISTS "prefix_CustomStylesheet" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
    "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
    "scope" TEXT NOT NULL DEFAULT 'GLOBAL',
    "css" TEXT NOT NULL DEFAULT '',
    CONSTRAINT "prefix_CustomStylesheet_scope_key" UNIQUE ("scope")
);

ALTER TABLE "prefix_CustomStylesheet" ENABLE ROW LEVEL SECURITY;

COMMENT ON TABLE "prefix_CustomStylesheet"
    IS 'Global custom CSS managed by admins and injected into all Agents Server pages.';

COMMENT ON COLUMN "prefix_CustomStylesheet"."scope"
    IS 'Singleton namespace key, currently always GLOBAL.';
