CREATE TABLE IF NOT EXISTS "prefix_CalendarConnection" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
    "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
    "userId" BIGINT NOT NULL,
    "agentPermanentId" TEXT NOT NULL,
    "provider" TEXT NOT NULL,
    "calendarUrl" TEXT NOT NULL,
    "calendarId" TEXT NOT NULL,
    "tokenRef" TEXT NOT NULL,
    "scopes" JSONB NOT NULL DEFAULT '[]'::jsonb,
    "status" TEXT NOT NULL DEFAULT 'CONNECTED',
    "disconnectedAt" TIMESTAMP WITH TIME ZONE NULL,
    "lastSyncedAt" TIMESTAMP WITH TIME ZONE NULL,
    CONSTRAINT "prefix_CalendarConnection_userId_fkey"
        FOREIGN KEY ("userId")
        REFERENCES "prefix_User"("id")
        ON DELETE CASCADE,
    CONSTRAINT "prefix_CalendarConnection_agentPermanentId_fkey"
        FOREIGN KEY ("agentPermanentId")
        REFERENCES "prefix_Agent"("permanentId")
        ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS "prefix_CalendarConnection_userId_idx"
    ON "prefix_CalendarConnection" ("userId");

CREATE INDEX IF NOT EXISTS "prefix_CalendarConnection_agentPermanentId_idx"
    ON "prefix_CalendarConnection" ("agentPermanentId");

CREATE INDEX IF NOT EXISTS "prefix_CalendarConnection_provider_idx"
    ON "prefix_CalendarConnection" ("provider");

CREATE INDEX IF NOT EXISTS "prefix_CalendarConnection_disconnectedAt_idx"
    ON "prefix_CalendarConnection" ("disconnectedAt");

CREATE UNIQUE INDEX IF NOT EXISTS "prefix_CalendarConnection_active_unique_idx"
    ON "prefix_CalendarConnection" ("userId", "agentPermanentId", "provider", "calendarUrl")
    WHERE "disconnectedAt" IS NULL;

CREATE TABLE IF NOT EXISTS "prefix_CalendarActivity" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
    "userId" BIGINT NULL,
    "agentPermanentId" TEXT NOT NULL,
    "connectionId" BIGINT NULL,
    "provider" TEXT NOT NULL,
    "operation" TEXT NOT NULL,
    "calendarUrl" TEXT NULL,
    "eventId" TEXT NULL,
    "status" TEXT NOT NULL,
    "details" JSONB NULL,
    CONSTRAINT "prefix_CalendarActivity_userId_fkey"
        FOREIGN KEY ("userId")
        REFERENCES "prefix_User"("id")
        ON DELETE SET NULL,
    CONSTRAINT "prefix_CalendarActivity_agentPermanentId_fkey"
        FOREIGN KEY ("agentPermanentId")
        REFERENCES "prefix_Agent"("permanentId")
        ON DELETE CASCADE,
    CONSTRAINT "prefix_CalendarActivity_connectionId_fkey"
        FOREIGN KEY ("connectionId")
        REFERENCES "prefix_CalendarConnection"("id")
        ON DELETE SET NULL
);

CREATE INDEX IF NOT EXISTS "prefix_CalendarActivity_agentPermanentId_createdAt_idx"
    ON "prefix_CalendarActivity" ("agentPermanentId", "createdAt" DESC);

CREATE INDEX IF NOT EXISTS "prefix_CalendarActivity_userId_createdAt_idx"
    ON "prefix_CalendarActivity" ("userId", "createdAt" DESC);
