CREATE TABLE IF NOT EXISTS "prefix_AgentProject" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
    "updatedAt" TIMESTAMP WITH TIME ZONE NULL DEFAULT now(),
    "agentPermanentId" TEXT NOT NULL,
    "name" TEXT NOT NULL,
    "directoryName" TEXT NOT NULL,
    "deletedAt" TIMESTAMP WITH TIME ZONE NULL,
    CONSTRAINT "prefix_AgentProject_agentPermanentId_fkey"
        FOREIGN KEY ("agentPermanentId")
        REFERENCES "prefix_Agent"("permanentId")
        ON DELETE CASCADE,
    CONSTRAINT "prefix_AgentProject_name_check"
        CHECK (length(trim("name")) > 0),
    CONSTRAINT "prefix_AgentProject_directoryName_check"
        CHECK (length(trim("directoryName")) > 0)
);

CREATE INDEX IF NOT EXISTS "prefix_AgentProject_agentPermanentId_idx"
    ON "prefix_AgentProject" ("agentPermanentId");

CREATE INDEX IF NOT EXISTS "prefix_AgentProject_deletedAt_idx"
    ON "prefix_AgentProject" ("deletedAt");

CREATE UNIQUE INDEX IF NOT EXISTS "prefix_AgentProject_agent_name_key"
    ON "prefix_AgentProject" ("agentPermanentId", "name")
    WHERE "deletedAt" IS NULL;

CREATE UNIQUE INDEX IF NOT EXISTS "prefix_AgentProject_agent_directoryName_key"
    ON "prefix_AgentProject" ("agentPermanentId", "directoryName")
    WHERE "deletedAt" IS NULL;

ALTER TABLE "prefix_AgentProject" ENABLE ROW LEVEL SECURITY;
