CREATE TABLE IF NOT EXISTS "prefix_KnowledgeSourceHashes" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
    "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),

    "source" TEXT NOT NULL,
    "hash" TEXT NOT NULL,
    "etag" TEXT,
    "lastModified" TEXT,
    "sizeBytes" BIGINT
);

CREATE UNIQUE INDEX IF NOT EXISTS "prefix_KnowledgeSourceHashes_source_idx"
    ON "prefix_KnowledgeSourceHashes" ("source");

ALTER TABLE "prefix_KnowledgeSourceHashes" ENABLE ROW LEVEL SECURITY;

CREATE TABLE IF NOT EXISTS "prefix_KnowledgeIndexCache" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
    "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),

    "hash" TEXT NOT NULL,
    "embeddingModel" TEXT NOT NULL,
    "sourceCount" INTEGER NOT NULL DEFAULT 0,
    "documentCount" INTEGER NOT NULL DEFAULT 0,
    "nodeCount" INTEGER NOT NULL DEFAULT 0,
    "payload" JSONB NOT NULL
);

CREATE UNIQUE INDEX IF NOT EXISTS "prefix_KnowledgeIndexCache_hash_idx"
    ON "prefix_KnowledgeIndexCache" ("hash");

ALTER TABLE "prefix_KnowledgeIndexCache" ENABLE ROW LEVEL SECURITY;
