CREATE TABLE IF NOT EXISTS "prefix_CustomJavascript" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
    "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
    "scope" TEXT NOT NULL DEFAULT 'GLOBAL',
    "javascript" TEXT NOT NULL DEFAULT '',
    CONSTRAINT "prefix_CustomJavascript_scope_key" UNIQUE ("scope")
);

ALTER TABLE "prefix_CustomJavascript" ENABLE ROW LEVEL SECURITY;

COMMENT ON TABLE "prefix_CustomJavascript"
    IS 'Global custom JavaScript managed by admins and injected into all Agents Server pages.';

COMMENT ON COLUMN "prefix_CustomJavascript"."scope"
    IS 'Singleton namespace key, currently always GLOBAL.';

COMMENT ON COLUMN "prefix_CustomJavascript"."javascript"
    IS 'Raw JavaScript text that runs on every agents server page when configured.';
