// ⚠️ WARNING: This code has been generated by `@promptbook/cli` so that any manual changes will be overwritten

import { createCollectionFromJson } from '../../collection/constructors/createCollectionFromJson';
import type { PipelineCollection } from '../../collection/PipelineCollection';

/**
 * Pipeline collection for Untitled Promptbook project
 *
 * ⚠️ WARNING: This code has been generated by `@promptbook/cli` so that any manual changes will be overwritten
 *
 * @private internal cache for `getTemplatesPipelineCollection`
 */
let pipelineCollection: null | PipelineCollection = null;


/**
 * Get pipeline collection for Untitled Promptbook project
 *
 * ⚠️ WARNING: This code has been generated by `@promptbook/cli` so that any manual changes will be overwritten
 *
 * @returns {PipelineCollection} Library of promptbooks for Untitled Promptbook project
 */
export function getTemplatesPipelineCollection(): PipelineCollection{
    if(pipelineCollection===null){
        pipelineCollection = createCollectionFromJson(
            {
                "title": "✨ Hello Book",
                "pipelineUrl": "https://github.com/webgptorg/book/blob/main/books/templates/generic.book.md",
                "formfactorName": "GENERIC",
                "parameters": [
                    {
                        "name": "letter",
                        "description": "Letter for you",
                        "isInput": false,
                        "isOutput": true
                    },
                    {
                        "name": "yourName",
                        "isInput": true,
                        "isOutput": false
                    }
                ],
                "tasks": [
                    {
                        "taskType": "PROMPT_TASK",
                        "name": "write-a-letter",
                        "title": "Write a letter",
                        "content": "Write a letter for {yourName}",
                        "resultingParameterName": "letter",
                        "personaName": "Jane",
                        "expectations": {
                            "words": {
                                "min": 3
                            },
                            "pages": {
                                "max": 1
                            }
                        },
                        "dependentParameterNames": [
                            "yourName"
                        ]
                    }
                ],
                "personas": [
                    {
                        "name": "Jane",
                        "description": "linguist and computer scientist",
                        "modelRequirements": {
                            "modelVariant": "CHAT",
                            "modelName": "gpt-4-turbo-2024-04-09",
                            "systemMessage": "You are a virtual assistant with expertise in linguistics and computer science. Provide accurate and insightful information on language structures, computational linguistics, programming languages, and the intersection of language and technology. Offer clear explanations and be ready to discuss both theoretical concepts and practical applications in these fields.",
                            "temperature": 0.7
                        },
                        "preparationIds": [
                            1
                        ]
                    }
                ],
                "preparations": [
                    {
                        "id": 1,
                        "promptbookVersion": "0.81.0-5",
                        "usage": {
                            "price": {
                                "value": 0.005451
                            },
                            "input": {
                                "tokensCount": {
                                    "value": 1167
                                },
                                "charactersCount": {
                                    "value": 3235
                                },
                                "wordsCount": {
                                    "value": 577
                                },
                                "sentencesCount": {
                                    "value": 53
                                },
                                "linesCount": {
                                    "value": 71
                                },
                                "paragraphsCount": {
                                    "value": 20
                                },
                                "pagesCount": {
                                    "value": 2
                                }
                            },
                            "output": {
                                "tokensCount": {
                                    "value": 130
                                },
                                "charactersCount": {
                                    "value": 572
                                },
                                "wordsCount": {
                                    "value": 79
                                },
                                "sentencesCount": {
                                    "value": 5
                                },
                                "linesCount": {
                                    "value": 15
                                },
                                "paragraphsCount": {
                                    "value": 2
                                },
                                "pagesCount": {
                                    "value": 1
                                }
                            }
                        }
                    }
                ],
                "knowledgeSources": [],
                "knowledgePieces": [],
                "sources": [
                    {
                        "type": "BOOK",
                        "path": null,
                        "content": "# ✨ Hello Book\n\n-   URL https://github.com/webgptorg/book/blob/main/books/templates/generic.book.md\n\n## Write a letter\n\n-   PERSONA Jane, linguist and computer scientist\n-   EXPECT MIN 3 Words\n-   EXPECT MAX 1 Page\n\n> Write a letter for {yourName}\n\n-> {letter} Letter for you\n"
                    }
                ],
                "sourceFile": "./book/books/templates/generic.book.md"
            }
        );
    }

    return pipelineCollection;
}
