CREATE TABLE IF NOT EXISTS "_Server" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "name" TEXT NOT NULL,
    "environment" "_ServerEnvironment" NOT NULL,
    "domain" TEXT NOT NULL,
    "tablePrefix" TEXT NOT NULL,
    "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
    "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()
);

CREATE UNIQUE INDEX IF NOT EXISTS "_Server_name_key" ON "_Server" ("name");
CREATE UNIQUE INDEX IF NOT EXISTS "_Server_domain_key" ON "_Server" ("domain");
CREATE UNIQUE INDEX IF NOT EXISTS "_Server_tablePrefix_key" ON "_Server" ("tablePrefix");

ALTER TABLE "_Server" ENABLE ROW LEVEL SECURITY;



INSERT INTO "_Server" ("name", "environment", "domain", "tablePrefix") VALUES 
('core.ptbk.io', 'PRODUCTION', 'core.ptbk.io', 'server_Core_'),
('core-test.ptbk.io', 'PREVIEW', 'core-test.ptbk.io', 'server_CoreTest_'),
('gallery.ptbk.io', 'PRODUCTION', 'gallery.ptbk.io', 'server_Gallery_'),
('dashboard.ptbk.io', 'PRODUCTION', 'dashboard.ptbk.io', 'server_Dashboard_'),
('landing-pages.ptbk.io', 'PRODUCTION', 'landing-pages.ptbk.io', 'server_LandingPages_'),
('demo.ptbk.io', 'PRODUCTION', 'demo.ptbk.io', 'server_Demo_'),
('s6.ptbk.io', 'PREVIEW', 's6.ptbk.io', 'server_S6_'),
('s7.ptbk.io', 'PREVIEW', 's7.ptbk.io', 'server_S7_'),
('s8.ptbk.io', 'PREVIEW', 's8.ptbk.io', 'server_S8_'),
('s9.ptbk.io', 'PREVIEW', 's9.ptbk.io', 'server_S9_'),
('s10.ptbk.io', 'PREVIEW', 's10.ptbk.io', 'server_S10_'),
('s11.ptbk.io', 'PREVIEW', 's11.ptbk.io', 'server_S11_'),
('s12.ptbk.io', 'PREVIEW', 's12.ptbk.io', 'server_S12_'),
('s13.ptbk.io', 'PREVIEW', 's13.ptbk.io', 'server_S13_'),
('pavol-hejny.ptbk.io', 'PREVIEW', 'pavol-hejny.ptbk.io', 'server_PavolHejny_'),
('jiri-jahn.ptbk.io', 'PRODUCTION', 'jiri-jahn.ptbk.io', 'server_JiriJahn_'),
('michal-novotny.ptbk.io', 'PRODUCTION', 'michal-novotny.ptbk.io', 'server_MichalNovotny_'),
('tomas-studenik.ptbk.io', 'PRODUCTION', 'tomas-studenik.ptbk.io', 'server_TomasStudenik_'),
('tomas-kapler.ptbk.io', 'PRODUCTION', 'tomas-kapler.ptbk.io', 'server_TomasKapler_'),
('praha13.ptbk.io', 'PRODUCTION', 'praha13.ptbk.io', 'server_Praha13_'),
('praha13-test.ptbk.io', 'PREVIEW', 'praha13-test.ptbk.io', 'server_Praha13Test_'),
('chutoo.ptbk.io', 'PRODUCTION', 'chutoo.ptbk.io', 'server_Chutoo_'),
('chutoo-test.ptbk.io', 'PREVIEW', 'chutoo-test.ptbk.io', 'server_ChutooTest_'),
('pasu.ptbk.io','PRODUCTION','pasu.ptbk.io','server_Pasu_'),
('pasu-test.ptbk.io','PREVIEW','pasu-test.ptbk.io','server_PasuTest_'),
('rymarov.ptbk.io','PRODUCTION','rymarov.ptbk.io','server_Rymarov_'),
('bizkithub.ptbk.io','PRODUCTION','bizkithub.ptbk.io','server_Bizkithub_'),
('vyjednavani.ptbk.io','PRODUCTION','vyjednavani.ptbk.io','server_Vyjednavani_'),
('neon-media.ptbk.io','PREVIEW','neon-media.ptbk.io','server_NeonMedia_');




/* [☁] !!!!!! */
