CREATE TABLE IF NOT EXISTS "_Server" (
     "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
    "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
    "name" TEXT NOT NULL UNIQUE,
    "environment" TEXT NOT NULL CHECK (environment IN ('PRODUCTION', 'PREVIEW')),
    "domain" TEXT NOT NULL,
    "tablePrefix" TEXT NOT NULL
);


/*


core.ptbk.io,core-test.ptbk.io,gallery.ptbk.io,dashboard.ptbk.io,landing-pages.ptbk.io,demo.ptbk.io,s6.ptbk.io,s7.ptbk.io,s8.ptbk.io,s9.ptbk.io,s10.ptbk.io,s11.ptbk.io,s12.ptbk.io,s13.ptbk.io,pavol-hejny.ptbk.io,jiri-jahn.ptbk.io,michal-novotny.ptbk.io,tomas-studenik.ptbk.io,tomas-kapler.ptbk.io,praha13.ptbk.io,praha13-test.ptbk.io,chutoo.ptbk.io,chutoo-test.ptbk.io,pasu.ptbk.io,rymarov.ptbk.io,bizkithub.ptbk.io,vyjednavani.ptbk.io,neon-media.ptbk.io



core.ptbk.io	Agents used in Promptbook itself 	Promptbook	Pavol	Production
core-test.ptbk.io	Agents used in Promptbook itself | Testing server	Promptbook	Pavol	Preview
gallery.ptbk.io	Gallery of ideas, AI professions,... like AI Agenta photobank 	Promptbook	Pavol	Production
				
dashboard.ptbk.io	Dashboard to see all agents from all servers 	Promptbook	Pavol	Production
landing-pages.ptbk.io	Agents to be used in landing pages	Promptbook	Pavol	Production
demo.ptbk.io	Demos to send for potential clients	Promptbook	Jiří	Production
				
s6.ptbk.io	General-purpose testing server 	~ Promptbook	Pavol	Preview
s7.ptbk.io	General-purpose testing server 	~ Promptbook	Pavol	Preview
s8.ptbk.io	General-purpose testing server 	~ Promptbook	Pavol	Preview
s9.ptbk.io	General-purpose testing server (Use for some client / isolated showcase in future)	~ Promptbook	Pavol	Preview
s10.ptbk.io	General-purpose testing server (Use for some client / isolated showcase in future)	~ Promptbook	Pavol	Preview
s11.ptbk.io	General-purpose testing server (Use for some client / isolated showcase in future)	~ Promptbook	Pavol	Preview
s12.ptbk.io	General-purpose testing server (Use for some client / isolated showcase in future)	~ Promptbook	Pavol	Preview
s13.ptbk.io	General-purpose testing server (Use for some client / isolated showcase in future)	~ Promptbook	Pavol	Preview
pavol-hejny.ptbk.io	Personal Pavol server to any testing, playing with Agents,...	Pavol	Pavol	Preview
jiri-jahn.ptbk.io	Personal Jirka server, playing with Agents,...	Jiří	Jiří	Production
michal-novotny.ptbk.io	Personal Michal server, playing with Agents,...	Michal	Michal	Production
tomas-studenik.ptbk.io		Tomáš Studeník	Tomáš	Production
tomas-kapler.ptbk.io		Tomáš Kapler	Tomáš	Production
praha13.ptbk.io	klient Praha 13 	Promptbook	Pavol	Production
praha13-test.ptbk.io	klient Praha 14	Promptbook	Pavol	Preview
chutoo.ptbk.io	Klient Chutoo	Chutoo	Pavol	Production
chutoo-test.ptbk.io	Klient Chutoo	Chutoo	Pavol	Preview
pasu.ptbk.io	Slezká Univerzita	Slezká Univerzita	Jiří	Production
pasu-test.ptbk.io	Slezká Univerzita	Slezká Univerzita	Jiří	Preview
rymarov.ptbk.io		Promptbook	Jiří	Production
bizkithub.ptbk.io	Honza Baršek	Jan Barášek  & Promptbook	Pavol	Production
vyjednavani.ptbk.io		X Oláh	Pavol	Production
				
				
neon-media.ptbk.io				Preview

*/


INSERT INTO "_Server" ("name", "environment", "domain", "tablePrefix") VALUES 
('core.ptbk.io', 'PRODUCTION', 'core.ptbk.io', 'core'),
('core-test.ptbk.io', 'PREVIEW', 'core-test.ptbk.io', 'core_test'),
('gallery.ptbk.io', 'PRODUCTION', 'gallery.ptbk.io', 'gallery'),
('dashboard.ptbk.io', 'PRODUCTION', 'dashboard.ptbk.io', 'dashboard'),
('landing-pages.ptbk.io', 'PRODUCTION', 'landing-pages.ptbk.io', 'landing_pages'),
('demo.ptbk.io', 'PRODUCTION', 'demo.ptbk.io', 'demo'),
('s6.ptbk.io', 'PREVIEW', 's6.ptbk.io', 's6'),
('s7.ptbk.io', 'PREVIEW', 's7.ptbk.io', 's7'),
('s8.ptbk.io', 'PREVIEW', 's8.ptbk.io', 's8'),
('s9.ptbk.io', 'PREVIEW', 's9.ptbk.io', 's9'),
('s10.ptbk.io', 'PREVIEW', 's10.ptbk.io', 's10'),
('s11.ptbk.io', 'PREVIEW', 's11.ptbk.io', 's11'),
('s12.ptbk.io', 'PREVIEW', 's12.ptbk.io', 's12'),
('s13.ptbk.io', 'PREVIEW', 's13.ptbk.io', 's13'),
('pavol-hejny.ptbk.io','PREVIEW','pavol-hejny.ptbk.io','pavol_hejny'),
('jiri-jahn.ptbk.io','PRODUCTION','jiri-jahn.ptbk.io','jiri_jahn'),
('michal-novotny.ptbk.io','PRODUCTION','michal-novotny.ptbk.io','michal_novotny'),
('tomas-studenik.ptbk.io','PRODUCTION','tomas-studenik.ptbk.io','tomas_studenik'),
('tomas-kapler.ptbk.io','PRODUCTION','tomas-kapler.ptbk.io','tomas_kapler'),
('praha13.ptbk.io','PRODUCTION','praha13.ptbk.io','praha13'),
('praha13-test.ptbk.io','PREVIEW','praha13-test.ptbk.io','praha13_test'),
('chutoo.ptbk.io','PRODUCTION','chutoo.ptbk.io','chutoo'),
('chutoo-test.ptbk.io','PREVIEW','chutoo-test.ptbk.io','chutoo_test'),
('pasu.ptbk.io','PRODUCTION','pasu.ptbk.io','pasu'),
('pasu-test.ptbk.io','PREVIEW','pasu-test.ptbk.io','pasu_test'),
('rymarov.ptbk.io','PRODUCTION','rymarov.ptbk.io','rymarov'),
('bizkithub.ptbk.io','PRODUCTION','bizkithub.ptbk.io','bizkithub'),
('vyjednavani.ptbk.io','PRODUCTION','vyjednavani.ptbk.io','vyjednavani'),
('neon-media.ptbk.io','PREVIEW','neon-media.ptbk.io','neon_media');


/* [☁] !!!!!! */
