
-- Note: This is primary source of truth for the database schema
--       In future we want to be compatible with more then Supabase so we keep SQL as main schema definition
--       To update, search for [💽]



CREATE TABLE IF NOT EXISTS "EnvironmentVariable" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "key" TEXT NOT NULL,
    "value" TEXT NOT NULL,
    "note" TEXT NULL,
    CONSTRAINT EnvironmentVariable_pkey PRIMARY KEY ("id"),
    CONSTRAINT EnvironmentVariable_key_key UNIQUE ("key")
);


CREATE TABLE IF NOT EXISTS "Agent" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "agentName" TEXT NOT NULL COMMENT 'The unique name of the agent derived from the first line of the `agentSource`, automatically updated on `agentSource` change',
    

    "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
    "updatedAt" TIMESTAMP WITH TIME ZONE NULL DEFAULT NULL,


    "agentHash" TEXT NOT NULL COMMENT 'The hash of the `agentSource`, automatically updated on `agentSource` change',
    "agentSource" TEXT NOT NULL COMMENT 'The source code of the agent',
    "agentProfile" JSONB NOT NULL COMMENT 'The profile of the agent generated from the `agentSource`, automatically updated on `agentSource` change',
    "promptbookEngineVersion" TEXT NOT NULL COMMENT 'The version of the Promptbook engine used for last update of the agent',
   
    "usage" JSONB NULL COMMENT 'Usage and spending statistics for the agent',
    "preparedModelRequirements" JSONB NULL COMMENT 'The prepared model requirements for the agent, generated from the `agentSource` but not after every change (only on explicit request), there is `agentHash` to identify the version of the `agentSource` this was prepared from',
    "preparedExternals" JSONB NULL COMMENT 'The prepared externals for the agent, generated from the `agentSource` but not after every change (only on explicit request), there is `agentHash` to identify the version of the `agentSource` this was prepared from',
    
    CONSTRAINT Agent_pkey PRIMARY KEY (id),
    CONSTRAINT Agent_agentName_key UNIQUE ("agentName")
);


CREATE TABLE IF NOT EXISTS "AgentHistory" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),

    "agentName" TEXT NOT NULL,
    "agentHash" TEXT NOT NULL,
    "previousAgentHash" TEXT NULL,
    "agentSource" TEXT NOT NULL,
    "promptbookEngineVersion" TEXT NOT NULL,
);


CREATE TABLE IF NOT EXISTS "ChatHistory" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),

    "messageHash" TEXT NOT NULL,
    "previousMessageHash" TEXT NULL,
    "agentName" TEXT NOT NULL,
    "agentHash" TEXT NOT NULL,
    "message" JSONB NOT NULL,

    -- Telemetry:
    "promptbookEngineVersion" TEXT NULL,
    "url" TEXT NULL COMMENT 'The URL where the chat was happening',
    "ip" TEXT NULL COMMENT 'The IP address of the user',
    "userAgent" TEXT NULL COMMENT 'The user agent (browser) of the user',
    "language" TEXT NULL COMMENT 'The language (from the browser) of the user',
    "platform" TEXT NULL COMMENT 'The platform of the user',
);


CREATE TABLE IF NOT EXISTS "ChatFeedback" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),

    "agentName" TEXT NOT NULL,
    "agentHash" TEXT NOT NULL,
    "rating" TEXT NULL,
    "textRating" TEXT NULL,
    "chatThread" TEXT NULL,
    "userNote" TEXT NULL,
    "expectedAnswer" TEXT NULL,

    -- Telemetry:
    "promptbookEngineVersion" TEXT NULL,
    "url" TEXT NULL COMMENT 'The URL where the chat was happening',
    "ip" TEXT NULL COMMENT 'The IP address of the user',
    "userAgent" TEXT NULL COMMENT 'The user agent (browser) of the user',
    "language" TEXT NULL COMMENT 'The language (from the browser) of the user',
    "platform" TEXT NULL COMMENT 'The platform of the user',
    constraint ChatFeedback_pkey primary key (id)
);


/*
CREATE TABLE IF NOT EXISTS "AgentActionHistory" (
id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
createdAt TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),

);
*/


/*
CREATE TABLE IF NOT EXISTS "Xxx" (
id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
);
*/


-- TODO: !!!! Create propper database migrations