
-- Note: This is primary source of truth for the database schema
--       In future we want to be compatible with more then Supabase so we keep SQL as main schema definition
--       To update, search for [💽]


CREATE TABLE IF NOT EXISTS "prefix_Metadata" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
    "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
    "key" TEXT NOT NULL,
    "value" TEXT NOT NULL,
    "note" TEXT NULL,
    CONSTRAINT prefix_Metadata_key_key UNIQUE ("key")
);

ALTER TABLE "prefix_Metadata" ENABLE ROW LEVEL SECURITY;


CREATE TABLE IF NOT EXISTS "prefix_Agent" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "agentName" TEXT NOT NULL,
    

    "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
    "updatedAt" TIMESTAMP WITH TIME ZONE NULL DEFAULT NULL,


    "agentHash" TEXT NOT NULL,
    "agentSource" TEXT NOT NULL,
    "agentProfile" JSONB NOT NULL,   
    "promptbookEngineVersion" TEXT NOT NULL,
   
    "usage" JSONB NULL,
    "preparedModelRequirements" JSONB NULL,
    "preparedExternals" JSONB NULL
);
-- Ensure uniqueness of agentName even on repeated schema application without duplicate constraint creation
CREATE UNIQUE INDEX IF NOT EXISTS prefix_agent_agentname_key ON "prefix_Agent" ("agentName");
COMMENT ON COLUMN "prefix_Agent"."agentName" IS 'The unique name of the agent derived from the first line of the `agentSource`, automatically updated on `agentSource` change';
COMMENT ON COLUMN "prefix_Agent"."agentHash" IS 'The hash of the `agentSource`, automatically updated on `agentSource` change';
COMMENT ON COLUMN "prefix_Agent"."agentSource" IS 'The source code of the agent';
COMMENT ON COLUMN "prefix_Agent"."agentProfile" IS 'The profile of the agent generated from the `agentSource`, automatically updated on `agentSource` change <- TODO: [🕛]';
COMMENT ON COLUMN "prefix_Agent"."promptbookEngineVersion" IS 'The version of the Promptbook engine used for last update of the agent';
COMMENT ON COLUMN "prefix_Agent"."usage" IS 'Usage and spending statistics for the agent';
COMMENT ON COLUMN "prefix_Agent"."preparedModelRequirements" IS 'The prepared model requirements for the agent, generated from the `agentSource` but not after every change (only on explicit request), there is `agentHash` to identify the version of the `agentSource` this was prepared from';
COMMENT ON COLUMN "prefix_Agent"."preparedExternals" IS 'The prepared externals for the agent, generated from the `agentSource` but not after every change (only on explicit request), there is `agentHash` to identify the version of the `agentSource` this was prepared from';

ALTER TABLE "prefix_Agent" ENABLE ROW LEVEL SECURITY;


CREATE TABLE IF NOT EXISTS "prefix_AgentHistory" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),

    "agentName" TEXT NOT NULL,
    "agentHash" TEXT NOT NULL,
    "previousAgentHash" TEXT NULL,
    "agentSource" TEXT NOT NULL,
    "promptbookEngineVersion" TEXT NOT NULL
    
);

CREATE INDEX IF NOT EXISTS "prefix_AgentHistory_agentName_idx" ON "prefix_AgentHistory" ("agentName");
CREATE INDEX IF NOT EXISTS "prefix_AgentHistory_agentHash_idx" ON "prefix_AgentHistory" ("agentHash");

ALTER TABLE "prefix_AgentHistory" ENABLE ROW LEVEL SECURITY;


CREATE TABLE IF NOT EXISTS "prefix_ChatHistory" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),

    "messageHash" TEXT NOT NULL,
    "previousMessageHash" TEXT NULL,
    "agentName" TEXT NOT NULL,
    "agentHash" TEXT NOT NULL,
    "message" JSONB NOT NULL,

    -- Telemetry:
    "promptbookEngineVersion" TEXT NULL,
    "url" TEXT NULL,
    "ip" TEXT NULL,
    "userAgent" TEXT NULL,
    "language" TEXT NULL,
    "platform" TEXT NULL
);
COMMENT ON COLUMN "prefix_ChatHistory"."url" IS 'The URL where the chat was happening';
COMMENT ON COLUMN "prefix_ChatHistory"."ip" IS 'The IP address of the user';
COMMENT ON COLUMN "prefix_ChatHistory"."userAgent" IS 'The user agent (browser) of the user';
COMMENT ON COLUMN "prefix_ChatHistory"."language" IS 'The language (from the browser) of the user';
COMMENT ON COLUMN "prefix_ChatHistory"."platform" IS 'The platform of the user';

ALTER TABLE "prefix_ChatHistory" ENABLE ROW LEVEL SECURITY;


CREATE TABLE IF NOT EXISTS "prefix_ChatFeedback" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),

    "agentName" TEXT NOT NULL,
    "agentHash" TEXT NOT NULL,
    "rating" TEXT NULL,
    "textRating" TEXT NULL,
    "chatThread" TEXT NULL,
    "userNote" TEXT NULL,
    "expectedAnswer" TEXT NULL,

    -- Telemetry:
    "promptbookEngineVersion" TEXT NULL,
    "url" TEXT NULL,
    "ip" TEXT NULL,
    "userAgent" TEXT NULL,
    "language" TEXT NULL,
    "platform" TEXT NULL
);
COMMENT ON COLUMN "prefix_ChatFeedback"."url" IS 'The URL where the chat was happening';
COMMENT ON COLUMN "prefix_ChatFeedback"."ip" IS 'The IP address of the user';
COMMENT ON COLUMN "prefix_ChatFeedback"."userAgent" IS 'The user agent (browser) of the user';
COMMENT ON COLUMN "prefix_ChatFeedback"."language" IS 'The language (from the browser) of the user';
COMMENT ON COLUMN "prefix_ChatFeedback"."platform" IS 'The platform of the user';

ALTER TABLE "prefix_ChatFeedback" ENABLE ROW LEVEL SECURITY;


CREATE TABLE IF NOT EXISTS "prefix_User" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
    "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
    
    "username" TEXT NOT NULL,
    "passwordHash" TEXT NOT NULL,
    "isAdmin" BOOLEAN NOT NULL DEFAULT FALSE
);
CREATE UNIQUE INDEX IF NOT EXISTS "prefix_User_username_idx" ON "prefix_User" ("username");

ALTER TABLE "prefix_User" ENABLE ROW LEVEL SECURITY;


/*
CREATE TABLE IF NOT EXISTS "prefix_AgentActionHistory" (
id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
createdAt TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),

);
*/


/*
CREATE TABLE IF NOT EXISTS "prefix_Xxx" (
id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
);
*/


-- Foreign key relationships
-- Note: Using agentName as the foreign key reference since it's the unique identifier used across tables
ALTER TABLE "prefix_AgentHistory" 
    DROP CONSTRAINT IF EXISTS "prefix_AgentHistory_agentName_fkey",
    ADD CONSTRAINT "prefix_AgentHistory_agentName_fkey" 
    FOREIGN KEY ("agentName") 
    REFERENCES "prefix_Agent"("agentName") 
    ON DELETE CASCADE;

ALTER TABLE "prefix_ChatHistory" 
    DROP CONSTRAINT IF EXISTS "prefix_ChatHistory_agentName_fkey",
    ADD CONSTRAINT "prefix_ChatHistory_agentName_fkey" 
    FOREIGN KEY ("agentName") 
    REFERENCES "prefix_Agent"("agentName") 
    ON DELETE CASCADE;

ALTER TABLE "prefix_ChatFeedback" 
    DROP CONSTRAINT IF EXISTS "prefix_ChatFeedback_agentName_fkey",
    ADD CONSTRAINT "prefix_ChatFeedback_agentName_fkey" 
    FOREIGN KEY ("agentName") 
    REFERENCES "prefix_Agent"("agentName") 
    ON DELETE CASCADE;

-- TODO: [🐱‍🚀] Create propper database migrations
