// Import all commitment definition classes
import { ActionCommitmentDefinition } from './ACTION/ACTION';
import { ClosedCommitmentDefinition } from './CLOSED/CLOSED';
import { ComponentCommitmentDefinition } from './COMPONENT/COMPONENT';
import { DeleteCommitmentDefinition } from './DELETE/DELETE';
import { FormatCommitmentDefinition } from './FORMAT/FORMAT';
import { FromCommitmentDefinition } from './FROM/FROM';
import { GoalCommitmentDefinition } from './GOAL/GOAL';
import { ImportantCommitmentDefinition } from './IMPORTANT/IMPORTANT';
import { KnowledgeCommitmentDefinition } from './KNOWLEDGE/KNOWLEDGE';
import { LanguageCommitmentDefinition } from './LANGUAGE/LANGUAGE';
import { MemoryCommitmentDefinition } from './MEMORY/MEMORY';
import { AgentMessageCommitmentDefinition } from './MESSAGE/AgentMessageCommitmentDefinition';
import { InitialMessageCommitmentDefinition } from './MESSAGE/InitialMessageCommitmentDefinition';
import { MessageCommitmentDefinition } from './MESSAGE/MESSAGE';
import { UserMessageCommitmentDefinition } from './MESSAGE/UserMessageCommitmentDefinition';
import { MetaCommitmentDefinition } from './META/META';
import { MetaColorCommitmentDefinition } from './META_COLOR/META_COLOR';
import { MetaImageCommitmentDefinition } from './META_IMAGE/META_IMAGE';
import { MetaLinkCommitmentDefinition } from './META_LINK/META_LINK';
import { ModelCommitmentDefinition } from './MODEL/MODEL';
import { NoteCommitmentDefinition } from './NOTE/NOTE';
import { OpenCommitmentDefinition } from './OPEN/OPEN';
import { PersonaCommitmentDefinition } from './PERSONA/PERSONA';
import { registerCommitment } from './registry';
import { RuleCommitmentDefinition } from './RULE/RULE';
import { SampleCommitmentDefinition } from './SAMPLE/SAMPLE';
import { ScenarioCommitmentDefinition } from './SCENARIO/SCENARIO';
import { StyleCommitmentDefinition } from './STYLE/STYLE';
import { NotYetImplementedCommitmentDefinition } from './_base/NotYetImplementedCommitmentDefinition';

// Register fully implemented commitments
registerCommitment(new PersonaCommitmentDefinition('PERSONA'));
registerCommitment(new PersonaCommitmentDefinition('PERSONAE'));
registerCommitment(new KnowledgeCommitmentDefinition());
registerCommitment(new MemoryCommitmentDefinition('MEMORY'));
registerCommitment(new MemoryCommitmentDefinition('MEMORIES'));
registerCommitment(new StyleCommitmentDefinition('STYLE'));
registerCommitment(new StyleCommitmentDefinition('STYLES'));
registerCommitment(new RuleCommitmentDefinition('RULE'));
registerCommitment(new RuleCommitmentDefinition('RULES'));
registerCommitment(new LanguageCommitmentDefinition('LANGUAGE'));
registerCommitment(new LanguageCommitmentDefinition('LANGUAGES'));
registerCommitment(new SampleCommitmentDefinition('SAMPLE'));
registerCommitment(new SampleCommitmentDefinition('EXAMPLE'));
registerCommitment(new FormatCommitmentDefinition('FORMAT'));
registerCommitment(new FormatCommitmentDefinition('FORMATS'));
registerCommitment(new FromCommitmentDefinition('FROM'));
registerCommitment(new ModelCommitmentDefinition('MODEL'));
registerCommitment(new ModelCommitmentDefinition('MODELS'));
registerCommitment(new ActionCommitmentDefinition('ACTION'));
registerCommitment(new ActionCommitmentDefinition('ACTIONS'));
registerCommitment(new ComponentCommitmentDefinition());
registerCommitment(new MetaImageCommitmentDefinition());
registerCommitment(new MetaColorCommitmentDefinition());
registerCommitment(new MetaLinkCommitmentDefinition());
registerCommitment(new MetaCommitmentDefinition());
registerCommitment(new NoteCommitmentDefinition('NOTE'));
registerCommitment(new NoteCommitmentDefinition('NOTES'));
registerCommitment(new NoteCommitmentDefinition('COMMENT'));
registerCommitment(new NoteCommitmentDefinition('NONCE'));
registerCommitment(new GoalCommitmentDefinition('GOAL'));
registerCommitment(new GoalCommitmentDefinition('GOALS'));
registerCommitment(new ImportantCommitmentDefinition());
registerCommitment(new InitialMessageCommitmentDefinition());
registerCommitment(new UserMessageCommitmentDefinition());
registerCommitment(new AgentMessageCommitmentDefinition());
registerCommitment(new MessageCommitmentDefinition('MESSAGE'));
registerCommitment(new MessageCommitmentDefinition('MESSAGES'));
registerCommitment(new ScenarioCommitmentDefinition('SCENARIO'));
registerCommitment(new ScenarioCommitmentDefinition('SCENARIOS'));
registerCommitment(new DeleteCommitmentDefinition('DELETE'));
registerCommitment(new DeleteCommitmentDefinition('CANCEL'));
registerCommitment(new DeleteCommitmentDefinition('DISCARD'));
registerCommitment(new DeleteCommitmentDefinition('REMOVE'));
registerCommitment(new OpenCommitmentDefinition());
registerCommitment(new ClosedCommitmentDefinition());

// Register not yet implemented commitments
registerCommitment(new NotYetImplementedCommitmentDefinition('EXPECT'));
registerCommitment(new NotYetImplementedCommitmentDefinition('BEHAVIOUR'));
registerCommitment(new NotYetImplementedCommitmentDefinition('BEHAVIOURS'));
registerCommitment(new NotYetImplementedCommitmentDefinition('AVOID'));
registerCommitment(new NotYetImplementedCommitmentDefinition('AVOIDANCE'));
registerCommitment(new NotYetImplementedCommitmentDefinition('CONTEXT'));

export * from './registry';
