import { describe, expect, it, jest } from '@jest/globals';
import spaceTrim from 'spacetrim';
import { validateBook } from '../../../../../src/book-2.0/agent-source/string_book';
import {
    appendMessageSuffix,
    createMessageSuffixAppendix,
    emulateMessageSuffixStreaming,
    resolveMessageSuffixFromAgentSource,
} from './messageSuffix';

describe('messageSuffix helpers', () => {
    it('resolves MESSAGE SUFFIX from agent source', () => {
        const messageSuffix = resolveMessageSuffixFromAgentSource(
            validateBook(
                spaceTrim(`
                    Branded Assistant
                    MESSAGE SUFFIX Generated by Promptbook.
                `),
            ),
        );

        expect(messageSuffix).toBe('Generated by Promptbook.');
    });

    it('creates suffix appendix with spacing for non-empty content', () => {
        expect(createMessageSuffixAppendix('Hello there.', 'Generated by Promptbook.')).toBe(
            '\n\nGenerated by Promptbook.',
        );
    });

    it('creates suffix appendix without leading spacing for empty content', () => {
        expect(createMessageSuffixAppendix('', 'Generated by Promptbook.')).toBe('Generated by Promptbook.');
    });

    it('appends suffix to content', () => {
        expect(appendMessageSuffix('Hello there.', 'Generated by Promptbook.')).toBe(
            'Hello there.\n\nGenerated by Promptbook.',
        );
    });

    it('emulates streaming by emitting deltas that reconstruct the full appendix', async () => {
        jest.useFakeTimers();

        const emittedDeltas: Array<string> = [];
        const streaming = emulateMessageSuffixStreaming('\n\nGenerated by Promptbook.', async (delta) => {
            emittedDeltas.push(delta);
        });

        await jest.runAllTimersAsync();
        await streaming;
        jest.useRealTimers();

        expect(emittedDeltas.join('')).toBe('\n\nGenerated by Promptbook.');
    });
});
