import type { DnsRecordsSection } from '../dnsRecords/DnsRecordsSection';
import { createEmailDnsInstructions } from './createEmailDnsInstructions';

/**
 * Creates the DNS section which makes agent email deliverable for one Agents Server domain.
 *
 * The DKIM records are intentionally not part of this section, because their public keys are generated by Stalwart
 * and have to be copied from its authoritative zone on `/admin/email-server`.
 *
 * @param options - Email domain, public VPS IP address, and the current mail DNS state.
 * @returns Email section.
 *
 * @private shared by the Agents Server DNS instruction views
 */
export function createEmailDnsRecordsSection(options: {
    /**
     * Domain which sends and receives the agent email.
     */
    readonly domain: string;

    /**
     * Public VPS IP address, when known by the server.
     */
    readonly publicIpAddress: string | null | undefined;

    /**
     * Current DNS verification state of the mail records, when it is known.
     */
    readonly statusSummary?: string | null;

    /**
     * Whether the mail records currently need attention.
     */
    readonly isDnsIssue?: boolean;
}): DnsRecordsSection {
    return {
        id: 'email',
        title: `Email for ${options.domain}`,
        description: options.publicIpAddress
            ? `Makes agent email deliverable. The A records use the detected public address of this VPS.`
            : `Makes agent email deliverable. Replace <VPS_PUBLIC_IP> with the public address of this VPS.`,
        variants: [
            {
                id: 'email',
                label: 'Email',
                recordSelection: 'all',
                records: createEmailDnsInstructions(options.domain, options.publicIpAddress),
            },
        ],
        statusSummary: options.statusSummary ?? null,
        isDnsIssue: options.isDnsIssue,
    };
}
