import { JSDOM } from 'jsdom';
import { assertSafeUrl } from '../assertSafeUrl';

/**
 * URL-bearing HTML attributes that can appear in standalone chat export markup.
 *
 * @private internal constant of chat PDF export sanitization
 */
const CHAT_PDF_EXPORT_URL_ATTRIBUTE_NAMES = new Set(['href', 'poster', 'src', 'xlink:href']);

/**
 * Protocols that cannot make the PDF renderer issue server-side network requests.
 *
 * @private internal constant of chat PDF export sanitization
 */
const CHAT_PDF_EXPORT_NON_NETWORK_PROTOCOLS = new Set(['about:', 'data:']);

/**
 * Link-only protocols that are safe to keep on anchors because Playwright does not fetch them while rendering.
 *
 * @private internal constant of chat PDF export sanitization
 */
const CHAT_PDF_EXPORT_LINK_ONLY_PROTOCOLS = new Set(['mailto:', 'tel:']);

/**
 * Matches CSS `url(...)` values inside inline styles and style blocks.
 *
 * @private internal constant of chat PDF export sanitization
 */
const CHAT_PDF_EXPORT_CSS_URL_FUNCTION_REGEX = /url\(\s*(['"]?)(.*?)\1\s*\)/gi;

/**
 * Parses the generated standalone chat export HTML and removes URL attributes
 * that would let Chromium reach private or unsupported destinations while
 * rendering the PDF.
 *
 * Markdown message bodies are already sanitized by the shared `renderMarkdown`
 * DOMPurify pipeline; this pass covers structured export URLs such as avatars,
 * citations, attachments, and markdown image `src` attributes after HTML
 * generation.
 *
 * @param html - Standalone chat export HTML generated by `buildChatHtml`.
 * @returns HTML safe to pass into the server-side PDF renderer.
 *
 * @private internal utility of the Agents Server chat PDF export route
 */
export function sanitizeChatPdfExportHtml(html: string): string {
    const dom = new JSDOM(html);
    const { document } = dom.window;

    for (const element of Array.from(document.querySelectorAll('*'))) {
        sanitizeChatPdfExportElementUrlAttributes(element);
        sanitizeChatPdfExportStyleAttribute(element);
    }

    for (const styleElement of Array.from(document.querySelectorAll('style'))) {
        styleElement.textContent = sanitizeChatPdfExportCssUrls(styleElement.textContent || '');
    }

    return dom.serialize();
}

/**
 * Removes unsafe URL attributes from one element.
 *
 * @param element - HTML element to sanitize.
 *
 * @private internal helper of `sanitizeChatPdfExportHtml`
 */
function sanitizeChatPdfExportElementUrlAttributes(element: Element): void {
    for (const attributeName of element.getAttributeNames()) {
        const normalizedAttributeName = attributeName.toLowerCase();

        if (!CHAT_PDF_EXPORT_URL_ATTRIBUTE_NAMES.has(normalizedAttributeName)) {
            continue;
        }

        const attributeValue = element.getAttribute(attributeName);

        if (
            attributeValue !== null &&
            !isSafeChatPdfExportUrl(attributeValue, isChatPdfExportNetworkRequestAttribute(element, attributeName))
        ) {
            element.removeAttribute(attributeName);
        }
    }
}

/**
 * Removes unsafe CSS `url(...)` values from one inline style attribute.
 *
 * @param element - HTML element whose style attribute should be sanitized.
 *
 * @private internal helper of `sanitizeChatPdfExportHtml`
 */
function sanitizeChatPdfExportStyleAttribute(element: Element): void {
    const styleValue = element.getAttribute('style');

    if (styleValue === null) {
        return;
    }

    element.setAttribute('style', sanitizeChatPdfExportCssUrls(styleValue));
}

/**
 * Replaces unsafe CSS `url(...)` functions with `none` so Chromium has no
 * private/internal resource to request while keeping unrelated inline styles.
 *
 * @param cssValue - CSS text from a style attribute or style element.
 * @returns CSS text without unsafe URL functions.
 *
 * @private internal helper of `sanitizeChatPdfExportHtml`
 */
function sanitizeChatPdfExportCssUrls(cssValue: string): string {
    return cssValue.replace(CHAT_PDF_EXPORT_CSS_URL_FUNCTION_REGEX, (rawMatch: string, _quote: string, url: string) => {
        if (isSafeChatPdfExportUrl(url, true)) {
            return rawMatch;
        }

        return 'none';
    });
}

/**
 * Returns whether an attribute value can be kept in the PDF-rendered HTML.
 *
 * Absolute HTTP(S) URLs are checked through the Agents Server SSRF guard.
 * Relative resource URLs are removed because server-side rendering has no
 * trusted origin for them, while relative anchor links remain useful inside the
 * PDF table of sources.
 *
 * @param rawUrl - Raw attribute or CSS URL value.
 * @param isNetworkRequestAttribute - Whether Chromium could fetch this value during rendering.
 * @returns Whether the URL value is safe to keep.
 *
 * @private internal helper of `sanitizeChatPdfExportHtml`
 */
function isSafeChatPdfExportUrl(rawUrl: string, isNetworkRequestAttribute: boolean): boolean {
    const trimmedUrl = rawUrl.trim();

    if (trimmedUrl === '' || trimmedUrl.startsWith('#')) {
        return true;
    }

    const absoluteUrl = trimmedUrl.startsWith('//') ? `https:${trimmedUrl}` : trimmedUrl;
    let parsedUrl: URL;
    try {
        parsedUrl = new URL(absoluteUrl);
    } catch {
        return !isNetworkRequestAttribute;
    }

    if (parsedUrl.protocol === 'http:' || parsedUrl.protocol === 'https:') {
        try {
            assertSafeUrl(absoluteUrl);
            return true;
        } catch {
            return false;
        }
    }

    if (CHAT_PDF_EXPORT_NON_NETWORK_PROTOCOLS.has(parsedUrl.protocol)) {
        return true;
    }

    return !isNetworkRequestAttribute && CHAT_PDF_EXPORT_LINK_ONLY_PROTOCOLS.has(parsedUrl.protocol);
}

/**
 * Returns whether one URL attribute can trigger a network request during PDF rendering.
 *
 * @param element - Element that owns the attribute.
 * @param attributeName - URL-bearing attribute name.
 * @returns Whether Chromium may fetch the attribute while rendering.
 *
 * @private internal helper of `sanitizeChatPdfExportHtml`
 */
function isChatPdfExportNetworkRequestAttribute(element: Element, attributeName: string): boolean {
    const normalizedAttributeName = attributeName.toLowerCase();

    if (normalizedAttributeName === 'src' || normalizedAttributeName === 'poster') {
        return true;
    }

    if (normalizedAttributeName === 'xlink:href') {
        return true;
    }

    return normalizedAttributeName === 'href' && element.tagName.toLowerCase() !== 'a';
}

// Note: [🟢] Code for Agents Server chat PDF export sanitization should never be published into packages that could be imported into browser environment
