import { Message } from '../../../types/Message';
import type { id, string_date_iso8601, string_markdown } from '../../../types/typeAliases';
import type { TODO_any } from '../../../utils/organization/TODO_any';

/**
 * Represents a single message within a chat interface.
 *
 * This type extends the base `Message` type by omitting internal routing fields
 * and adding chat-specific properties like markdown content and generation status.
 *
 * @public exported from `@promptbook/components`
 */
export type ChatMessage = Omit<Message<id>, 'direction' | 'recipients' | 'threadId' | 'metadata'> & {
    /**
     * Force the channel to be 'PROMPTBOOK_CHAT'
     *
     * @default 'PROMPTBOOK_CHAT'
     */
    channel?: 'PROMPTBOOK_CHAT';

    /**
     * The content of the message with optional markdown formatting
     */
    content: string_markdown;

    /**
     * Whether the message is complete (for example, if it's still being generated by an AI)
     *
     * @default true
     */
    isComplete?: boolean;

    /**
     * The expected answer for the message (used for testing or validation)
     */
    expectedAnswer?: string;

    /**
     * Indicates if the message was sent via a voice call
     */
    isVoiceCall?: boolean;

    /**
     * Optional tool calls made during the execution
     */
    readonly ongoingToolCalls?: ReadonlyArray<{
        /**
         * Name of the tool
         */
        readonly name: string;

        /**
         * Arguments for the tool call
         */
        readonly arguments?: string | Record<string, TODO_any>;

        /**
         * Result of the tool call
         */
        readonly result?: TODO_any;

        /**
         * Raw tool call from the model
         */
        readonly rawToolCall?: TODO_any;
    }>;

    /**
     * Optional tool calls that have been completed
     */
    readonly completedToolCalls?: ReadonlyArray<{
        /**
         * Name of the tool
         */
        readonly name: string;

        /**
         * Arguments for the tool call
         */
        readonly arguments?: string | Record<string, TODO_any>;

        /**
         * Result of the tool call
         */
        readonly result?: TODO_any;

        /**
         * Raw tool call from the model
         */
        readonly rawToolCall?: TODO_any;

        /**
         * Date when the tool call was completed
         */
        readonly createdAt?: Date | string_date_iso8601;
    }>;

    /**
     * Optional file attachments
     */
    attachments?: Array<{
        /**
         * The name of the file
         */
        name: string;

        /**
         * The type of the file
         */
        type: string;

        /**
         * The URL where the file is stored
         */
        url: string;
    }>;
};

/**
 * TODO: Make all fields readonly
 * TODO: Delete `expectedAnswer` from ChatMessage
 * TODO: Rename `date` into `created`+`modified`
 */
