import type { id, string_markdown } from '../../../types/typeAliases';

/**
 * A message in the chat
 *
 * @public exported from `@promptbook/components`
 */
export type ChatMessage = {
    /**
     * Unique identifier of the message
     */
    id?: id;

    /**
     * Date when the message was created
     */
    date?: Date;

    /**
     * The name of the participant who sent the message
     */
    from: id;

    /**
     * The content of the message with optional markdown formatting
     */
    content: string_markdown;

    /**
     * Whether the message is complete (for example, if it's still being generated by an AI)
     *
     * @default true
     */
    isComplete?: boolean;

    /**
     * @@@
     */
    expectedAnswer?: string;

    /**
     * @@@
     */
    isVoiceCall?: boolean;

    /**
     * Whether the message was generated from an outdated source
     * 
     * When the agent source changes (e.g., editing the book), existing messages
     * are marked as outdated to indicate they were generated with a previous version
     * 
     * @default false
     */
    isFromOutdatedSource?: boolean;
};

/**
 * TODO: Delete `expectedAnswer` from ChatMessage
 * TODO: Rename `date` into `created`+`modified`
 */
