import { Message } from '../../../types/Message';
import type { id, string_markdown } from '../../../types/typeAliases';

/**
 * A message in the chat
 *
 * @public exported from `@promptbook/components`
 */
export type ChatMessage = Omit<Message<id>, 'direction' | 'recipients' | 'threadId' | 'metadata'> & {
    /**
     * Force the channel to be 'PROMPTBOOK_CHAT'
     *
     * !!!! Make it non mandatory
     */
    channel: 'PROMPTBOOK_CHAT';

    /**
     * The content of the message with optional markdown formatting
     */
    content: string_markdown;

    /**
     * Whether the message is complete (for example, if it's still being generated by an AI)
     *
     * @default true
     */
    isComplete?: boolean;

    /**
     * @@@
     */
    expectedAnswer?: string;

    /**
     * @@@
     */
    isVoiceCall?: boolean;
};

/**
 * TODO: Make all fields readonly
 * TODO: Delete `expectedAnswer` from ChatMessage
 * TODO: Rename `date` into `created`+`modified`
 */
