import { spaceTrim } from 'spacetrim';
import type { PromptbookString } from '../../types/PromptbookString';
import { addAutoGeneratedSection } from '../../utils/markdown/addAutoGeneratedSection';
import { prettifyMarkdown } from '../../utils/markdown/prettifyMarkdown';
import { promptbookStringToJson } from '../promptbookStringToJson';
import type { PrettifyOptions } from './PrettifyOptions';
import { renderPromptbookMermaid } from './renderPromptbookMermaid';

/**
 * Prettyfies Promptbook string and adds Mermaid graph
 */
export async function prettifyPromptbookString(
    promptbookString: PromptbookString,
    options: PrettifyOptions,
): Promise<PromptbookString> {
    const { isGraphAdded, isPrettifyed } = options;

    if (isGraphAdded) {
        const promptbookJson = await promptbookStringToJson(promptbookString /* , {!!!!} */);

        const promptbookMermaid = renderPromptbookMermaid(promptbookJson, {
            linkPromptTemplate(promptTemplate) {
                return { href: `#${promptTemplate.name}`, title: promptTemplate.title };
            },
        });

        const promptbookMermaidBlock = spaceTrim(
            (block) => `
            \`\`\`mermaid
            ${block(promptbookMermaid)}
            \`\`\`
        `,
        );

        promptbookString = addAutoGeneratedSection(promptbookString, {
            sectionName: 'Graph',
            sectionContent: promptbookMermaidBlock,
        }) as PromptbookString;
    }

    if (isPrettifyed) {
        promptbookString = prettifyMarkdown(promptbookString) as PromptbookString;
    }

    return promptbookString;
}

/**
 * TODO: Maybe use some Mermaid library instead of string templating
 * TODO: [🕌] When more than 2 functionalities, split into separate functions
 */
