### Get the book

GET http://localhost:4440/agents/Gabriel%20Gray/api/book



# _______________________________________
### Update the book 1


PUT http://localhost:4440/agents/Gabriel%20Gray/api/book
Content-Type: text/plain
# <- TODO: [🎳] Mime type of book


Gabriel Gray

META COLOR #c9c9c9
PERSONA Friendly and helpful AI agent.
RULE Be kind and respectful.




# _______________________________________
### Update the book 2


PUT http://localhost:4440/agents/Gabriel%20Gray/api/book
Content-Type: text/plain
# <- TODO: [🎳] Mime type of book

Gabriel Gray

META COLOR #242424
PERSONA Strict and professional AI agent.
RULE Be strict and professional.