import type { string_markdown, string_name } from '../../types/typeAliases';
/**
 * Add or modify an auto-generated section in a markdown file
 *
 * @public exported from `@promptbook/markdown-utils`
 */
export declare function addAutoGeneratedSection(content: string_markdown, options: {
    readonly sectionName: string_name;
    readonly sectionContent: string_markdown;
}): string_markdown;
/**
 * TODO: [🏛] This can be part of markdown builder
 */
