import { readFile } from 'fs/promises';
import { extname, relative, resolve } from 'path';
import type { SourceFile } from 'typescript';
import * as ts from 'typescript';
import {
    DEFAULT_MAX_LINE_COUNT,
    ENTITY_COUNT_EXTENSIONS,
    GENERATED_CODE_MARKERS,
    LINE_COUNT_LIMITS_BY_EXTENSION,
    MAX_ENTITIES_PER_FILE,
} from './find-refactor-candidates.constants';
import type { RefactorCandidate } from './RefactorCandidate';
import { normalizeRefactorCandidatePath } from './normalizeRefactorCandidatePath';

/**
 * Input required to analyze one source file for refactor candidacy.
 *
 * @private type of findRefactorCandidates
 */
export type AnalyzeSourceFileForRefactorCandidateOptions = {
    /**
     * Absolute path to the source file.
     */
    readonly filePath: string;

    /**
     * Repository root used for relative path generation.
     */
    readonly rootDir: string;

    /**
     * Normalized absolute paths exempt from line-count checks.
     */
    readonly lineCountExemptPaths: ReadonlySet<string>;
};

/**
 * Resolves whether a source file should produce a refactor candidate entry.
 *
 * @private function of findRefactorCandidates
 */
export async function analyzeSourceFileForRefactorCandidate(
    options: AnalyzeSourceFileForRefactorCandidateOptions,
): Promise<RefactorCandidate | null> {
    const { filePath, lineCountExemptPaths, rootDir } = options;
    const normalizedAbsolutePath = normalizeAbsolutePath(filePath);
    const content = await readFile(filePath, 'utf-8');

    if (isGeneratedFile(content)) {
        return null;
    }

    const extension = extname(filePath).toLowerCase();
    const relativePath = normalizeRefactorCandidatePath(relative(rootDir, filePath));
    const reasons: string[] = [];

    if (!lineCountExemptPaths.has(normalizedAbsolutePath)) {
        const lineCount = countLines(content);
        const maxLines = getMaxLinesForExtension(extension);

        if (lineCount > maxLines) {
            reasons.push(`lines ${lineCount}/${maxLines}`);
        }
    }

    if (ENTITY_COUNT_EXTENSIONS.includes(extension)) {
        const entityCount = countEntities(content, extension, filePath);
        if (entityCount > MAX_ENTITIES_PER_FILE) {
            reasons.push(`entities ${entityCount}/${MAX_ENTITIES_PER_FILE}`);
        }
    }

    if (reasons.length === 0) {
        return null;
    }

    return {
        absolutePath: filePath,
        relativePath,
        reasons,
    };
}

/**
 * Determines whether a file is generated by scanning for known markers.
 *
 * @private function of analyzeSourceFileForRefactorCandidate
 */
function isGeneratedFile(content: string): boolean {
    return GENERATED_CODE_MARKERS.some((marker) => content.includes(marker));
}

/**
 * Gets the maximum allowed lines for a file extension.
 *
 * @private function of analyzeSourceFileForRefactorCandidate
 */
function getMaxLinesForExtension(extension: string): number {
    return LINE_COUNT_LIMITS_BY_EXTENSION[extension] ?? DEFAULT_MAX_LINE_COUNT;
}

/**
 * Counts lines while ignoring a trailing newline.
 *
 * @private function of analyzeSourceFileForRefactorCandidate
 */
function countLines(content: string): number {
    if (content.length === 0) {
        return 0;
    }

    const lines = content.split(/\r?\n/);
    return lines[lines.length - 1] === '' ? lines.length - 1 : lines.length;
}

/**
 * Counts top-level entities in a source file.
 *
 * @private function of analyzeSourceFileForRefactorCandidate
 */
function countEntities(content: string, extension: string, filePath: string): number {
    const scriptKind = getScriptKindForExtension(extension);
    const sourceFile = ts.createSourceFile(filePath, content, ts.ScriptTarget.Latest, false, scriptKind);
    return countEntitiesInSourceFile(sourceFile);
}

/**
 * Counts top-level entities in a parsed TypeScript source file.
 *
 * @private function of analyzeSourceFileForRefactorCandidate
 */
function countEntitiesInSourceFile(sourceFile: SourceFile): number {
    let count = 0;

    // Only count top-level declarations to avoid inflating with members or nested scopes.
    for (const statement of sourceFile.statements) {
        if (
            ts.isFunctionDeclaration(statement) ||
            ts.isClassDeclaration(statement) ||
            ts.isInterfaceDeclaration(statement) ||
            ts.isTypeAliasDeclaration(statement) ||
            ts.isEnumDeclaration(statement) ||
            ts.isModuleDeclaration(statement)
        ) {
            count += 1;
            continue;
        }

        if (ts.isVariableStatement(statement)) {
            for (const declaration of statement.declarationList.declarations) {
                const initializer = declaration.initializer;

                if (
                    initializer &&
                    (ts.isArrowFunction(initializer) ||
                        ts.isFunctionExpression(initializer) ||
                        ts.isClassExpression(initializer))
                ) {
                    count += 1;
                }
            }
        }
    }

    return count;
}

/**
 * Resolves the script kind for a source file extension.
 *
 * @private function of analyzeSourceFileForRefactorCandidate
 */
function getScriptKindForExtension(extension: string): ts.ScriptKind {
    if (extension === '.tsx') {
        return ts.ScriptKind.TSX;
    }

    if (extension === '.jsx') {
        return ts.ScriptKind.JSX;
    }

    if (extension === '.js') {
        return ts.ScriptKind.JS;
    }

    return ts.ScriptKind.TS;
}

/**
 * Normalizes an absolute path for consistent comparisons.
 *
 * @private function of analyzeSourceFileForRefactorCandidate
 */
function normalizeAbsolutePath(pathValue: string): string {
    const normalized = resolve(pathValue);
    return process.platform === 'win32' ? normalized.toLowerCase() : normalized;
}

/** Note: [🟡] Code for repository script [analyzeSourceFileForRefactorCandidate](scripts/find-refactor-candidates/analyzeSourceFileForRefactorCandidate.ts) should never be published outside of `@promptbook/cli` */
