import { readFile } from 'fs/promises';
import { extname, relative, resolve } from 'path';
import type { SourceFile } from 'typescript';
import type * as TypescriptModule from 'typescript';
import { getTypescriptModule } from '../../src/cli/cli-commands/coder/getTypescriptModule';
import { UnexpectedError } from '../../src/errors/UnexpectedError';
import { spaceTrim } from '../../src/utils/organization/spaceTrim';
import {
    GENERATED_CODE_MARKERS,
    STRUCTURAL_ANALYSIS_EXTENSIONS,
} from './find-refactor-candidates.constants';
import type { RefactorCandidate } from './RefactorCandidate';
import type { RefactorCandidateLevelConfiguration } from './RefactorCandidateLevel';
import { normalizeRefactorCandidatePath } from './normalizeRefactorCandidatePath';

/**
 * The TypeScript compiler API once it was loaded by `analyzeSourceFileForRefactorCandidate`
 *
 * Note: [🐌] `typescript` is a heavy package, it is loaded on demand so that it does not slow down every single run
 *       of the `ptbk` CLI utility
 *
 * @private variable of analyzeSourceFileForRefactorCandidate
 */
let loadedTypescriptModule: typeof TypescriptModule | null = null;

/**
 * Returns the TypeScript compiler API which was already loaded for the structural analysis.
 *
 * @private function of analyzeSourceFileForRefactorCandidate
 */
function getLoadedTypescriptModule(): typeof TypescriptModule {
    if (loadedTypescriptModule === null) {
        throw new UnexpectedError(
            spaceTrim(`
                The \`typescript\` module was not loaded yet.

                Structural analysis helpers must be called only from \`analyzeSourceFileForRefactorCandidate\` which
                loads \`typescript\` lazily.
            `),
        );
    }

    return loadedTypescriptModule;
}

/**
 * Input required to analyze one source file for refactor candidacy.
 *
 * @private type of findRefactorCandidates
 */
export type AnalyzeSourceFileForRefactorCandidateOptions = {
    /**
     * Absolute path to the source file.
     */
    readonly filePath: string;

    /**
     * Repository root used for relative path generation.
     */
    readonly rootDir: string;

    /**
     * Normalized absolute paths exempt from line-count checks.
     */
    readonly lineCountExemptPaths: ReadonlySet<string>;

    /**
     * Thresholds used to decide whether the file should be flagged.
     */
    readonly heuristics: RefactorCandidateLevelConfiguration;
};

/**
 * Resolves whether a source file should produce a refactor candidate entry.
 *
 * @private function of findRefactorCandidates
 */
export async function analyzeSourceFileForRefactorCandidate(
    options: AnalyzeSourceFileForRefactorCandidateOptions,
): Promise<RefactorCandidate | null> {
    const { filePath, heuristics, lineCountExemptPaths, rootDir } = options;
    const normalizedAbsolutePath = normalizeAbsolutePath(filePath);
    const content = await readFile(filePath, 'utf-8');

    if (isGeneratedFile(content)) {
        return null;
    }

    const extension = extname(filePath).toLowerCase();
    const relativePath = normalizeRefactorCandidatePath(relative(rootDir, filePath));
    const reasons: string[] = [];
    let severityScore = 0;

    if (!lineCountExemptPaths.has(normalizedAbsolutePath)) {
        const lineCount = countLines(content);
        const maxLines = getMaxLinesForExtension(extension, heuristics);

        if (lineCount > maxLines) {
            reasons.push(`lines ${lineCount}/${maxLines}`);
            severityScore += lineCount / maxLines;
        }
    }

    if (STRUCTURAL_ANALYSIS_EXTENSIONS.includes(extension)) {
        loadedTypescriptModule ??= await getTypescriptModule();

        const structureSummary = summarizeSourceFileStructure(content, extension, filePath);

        if (structureSummary.entityCount > heuristics.maxEntityCountPerFile) {
            reasons.push(`entities ${structureSummary.entityCount}/${heuristics.maxEntityCountPerFile}`);
            severityScore += structureSummary.entityCount / heuristics.maxEntityCountPerFile;
        }

        if (structureSummary.functionCount > heuristics.maxFunctionCountPerFile) {
            reasons.push(`functions ${structureSummary.functionCount}/${heuristics.maxFunctionCountPerFile}`);
            severityScore += structureSummary.functionCount / heuristics.maxFunctionCountPerFile;
        }

        if (structureSummary.maxFunctionComplexity > heuristics.maxFunctionComplexity) {
            reasons.push(buildComplexityReason(structureSummary, heuristics.maxFunctionComplexity));
            severityScore += structureSummary.maxFunctionComplexity / heuristics.maxFunctionComplexity;
        }
    }

    if (reasons.length === 0) {
        return null;
    }

    return {
        absolutePath: filePath,
        relativePath,
        reasons,
        severityScore,
    };
}

/**
 * Determines whether a file is generated by scanning for known markers.
 *
 * @private function of analyzeSourceFileForRefactorCandidate
 */
function isGeneratedFile(content: string): boolean {
    return GENERATED_CODE_MARKERS.some((marker) => content.includes(marker));
}

/**
 * Gets the maximum allowed lines for a file extension.
 *
 * @private function of analyzeSourceFileForRefactorCandidate
 */
function getMaxLinesForExtension(extension: string, heuristics: RefactorCandidateLevelConfiguration): number {
    return heuristics.maxLineCountByExtension[extension] ?? heuristics.maxDefaultLineCount;
}

/**
 * Counts lines while ignoring a trailing newline.
 *
 * @private function of analyzeSourceFileForRefactorCandidate
 */
function countLines(content: string): number {
    if (content.length === 0) {
        return 0;
    }

    const lines = content.split(/\r?\n/);
    return lines[lines.length - 1] === '' ? lines.length - 1 : lines.length;
}

/**
 * Summarizes the structural metrics used to score one source file.
 *
 * @private function of analyzeSourceFileForRefactorCandidate
 */
function summarizeSourceFileStructure(content: string, extension: string, filePath: string): SourceFileStructureSummary {
    const ts = getLoadedTypescriptModule();
    const scriptKind = getScriptKindForExtension(extension);
    const sourceFile = ts.createSourceFile(filePath, content, ts.ScriptTarget.Latest, true, scriptKind);

    return {
        entityCount: countEntitiesInSourceFile(sourceFile),
        ...summarizeFunctionsInSourceFile(sourceFile),
    };
}

/**
 * Counts top-level entities in a parsed TypeScript source file.
 *
 * @private function of analyzeSourceFileForRefactorCandidate
 */
function countEntitiesInSourceFile(sourceFile: SourceFile): number {
    const ts = getLoadedTypescriptModule();
    let count = 0;

    // Only count top-level declarations to avoid inflating with members or nested scopes.
    for (const statement of sourceFile.statements) {
        if (
            ts.isFunctionDeclaration(statement) ||
            ts.isClassDeclaration(statement) ||
            ts.isInterfaceDeclaration(statement) ||
            ts.isTypeAliasDeclaration(statement) ||
            ts.isEnumDeclaration(statement) ||
            ts.isModuleDeclaration(statement)
        ) {
            count += 1;
            continue;
        }

        if (ts.isVariableStatement(statement)) {
            for (const declaration of statement.declarationList.declarations) {
                const initializer = declaration.initializer;

                if (
                    initializer &&
                    (ts.isArrowFunction(initializer) ||
                        ts.isFunctionExpression(initializer) ||
                        ts.isClassExpression(initializer))
                ) {
                    count += 1;
                }
            }
        }
    }

    return count;
}

/**
 * Structural metrics derived from function-like declarations in a source file.
 *
 * @private type of analyzeSourceFileForRefactorCandidate
 */
type SourceFileFunctionSummary = {
    /**
     * Number of named functions and methods found in the file.
     */
    readonly functionCount: number;

    /**
     * Highest complexity score found among the functions in the file.
     */
    readonly maxFunctionComplexity: number;

    /**
     * Name of the most complex function when one can be resolved.
     */
    readonly mostComplexFunctionName: string | null;
};

/**
 * Structural metrics derived from the parsed source file.
 *
 * @private type of analyzeSourceFileForRefactorCandidate
 */
type SourceFileStructureSummary = {
    /**
     * Number of top-level entities found in the file.
     */
    readonly entityCount: number;

    /**
     * Function metrics collected from the file.
     */
    readonly functionCount: number;

    /**
     * Highest function complexity found in the file.
     */
    readonly maxFunctionComplexity: number;

    /**
     * Name of the most complex function when one can be resolved.
     */
    readonly mostComplexFunctionName: string | null;
};

/**
 * Function-like declarations counted for file-level function density.
 *
 * @private type of analyzeSourceFileForRefactorCandidate
 */
type CountedFunctionLikeDeclaration =
    | TypescriptModule.ArrowFunction
    | TypescriptModule.ConstructorDeclaration
    | TypescriptModule.FunctionDeclaration
    | TypescriptModule.FunctionExpression
    | TypescriptModule.GetAccessorDeclaration
    | TypescriptModule.MethodDeclaration
    | TypescriptModule.SetAccessorDeclaration;

/**
 * Summarizes named functions and methods in a parsed source file.
 *
 * @private function of analyzeSourceFileForRefactorCandidate
 */
function summarizeFunctionsInSourceFile(sourceFile: SourceFile): SourceFileFunctionSummary {
    const ts = getLoadedTypescriptModule();
    let functionCount = 0;
    let maxFunctionComplexity = 0;
    let mostComplexFunctionName: string | null = null;

    const visitNode = (node: TypescriptModule.Node): void => {
        if (isCountedFunctionLikeDeclaration(node)) {
            functionCount += 1;

            const functionComplexity = calculateFunctionComplexity(node);
            if (functionComplexity > maxFunctionComplexity) {
                maxFunctionComplexity = functionComplexity;
                mostComplexFunctionName = getFunctionDisplayName(node);
            }
        }

        ts.forEachChild(node, visitNode);
    };

    visitNode(sourceFile);

    return {
        functionCount,
        maxFunctionComplexity,
        mostComplexFunctionName,
    };
}

/**
 * Determines whether a node counts as a named function or method for density checks.
 *
 * @private function of analyzeSourceFileForRefactorCandidate
 */
function isCountedFunctionLikeDeclaration(node: TypescriptModule.Node): node is CountedFunctionLikeDeclaration {
    const ts = getLoadedTypescriptModule();

    if (
        ts.isFunctionDeclaration(node) ||
        ts.isMethodDeclaration(node) ||
        ts.isConstructorDeclaration(node) ||
        ts.isGetAccessorDeclaration(node) ||
        ts.isSetAccessorDeclaration(node)
    ) {
        return true;
    }

    if (ts.isArrowFunction(node) || ts.isFunctionExpression(node)) {
        return isNamedFunctionExpression(node);
    }

    return false;
}

/**
 * Determines whether a function expression is attached to a named variable or property.
 *
 * @private function of analyzeSourceFileForRefactorCandidate
 */
function isNamedFunctionExpression(
    node: TypescriptModule.ArrowFunction | TypescriptModule.FunctionExpression,
): boolean {
    const ts = getLoadedTypescriptModule();
    const parent = node.parent;

    return (
        ts.isVariableDeclaration(parent) || ts.isPropertyDeclaration(parent) || ts.isPropertyAssignment(parent)
    );
}

/**
 * Calculates a lightweight cyclomatic-complexity score for one function.
 *
 * @private function of analyzeSourceFileForRefactorCandidate
 */
function calculateFunctionComplexity(functionNode: CountedFunctionLikeDeclaration): number {
    if (!functionNode.body) {
        return 1;
    }

    const ts = getLoadedTypescriptModule();
    let complexity = 1;

    const visitNode = (node: TypescriptModule.Node): void => {
        if (node !== functionNode.body && isCountedFunctionLikeDeclaration(node)) {
            return;
        }

        if (isComplexityDecisionNode(node)) {
            complexity += 1;
        }

        ts.forEachChild(node, visitNode);
    };

    visitNode(functionNode.body);

    return complexity;
}

/**
 * Determines whether a node should increase the complexity score.
 *
 * @private function of analyzeSourceFileForRefactorCandidate
 */
function isComplexityDecisionNode(node: TypescriptModule.Node): boolean {
    const ts = getLoadedTypescriptModule();

    if (
        ts.isIfStatement(node) ||
        ts.isConditionalExpression(node) ||
        ts.isCatchClause(node) ||
        ts.isForStatement(node) ||
        ts.isForInStatement(node) ||
        ts.isForOfStatement(node) ||
        ts.isWhileStatement(node) ||
        ts.isDoStatement(node) ||
        ts.isCaseClause(node)
    ) {
        return true;
    }

    if (ts.isBinaryExpression(node)) {
        const operatorKind = node.operatorToken.kind;

        return (
            operatorKind === ts.SyntaxKind.AmpersandAmpersandToken ||
            operatorKind === ts.SyntaxKind.BarBarToken ||
            operatorKind === ts.SyntaxKind.QuestionQuestionToken
        );
    }

    return false;
}

/**
 * Resolves a readable display name for a counted function-like declaration.
 *
 * @private function of analyzeSourceFileForRefactorCandidate
 */
function getFunctionDisplayName(functionNode: CountedFunctionLikeDeclaration): string | null {
    const ts = getLoadedTypescriptModule();

    if (ts.isConstructorDeclaration(functionNode)) {
        return 'constructor';
    }

    if (
        ts.isFunctionDeclaration(functionNode) ||
        ts.isMethodDeclaration(functionNode) ||
        ts.isGetAccessorDeclaration(functionNode) ||
        ts.isSetAccessorDeclaration(functionNode)
    ) {
        if (!functionNode.name) {
            return null;
        }

        return getPropertyNameText(functionNode.name);
    }

    if (ts.isArrowFunction(functionNode) || ts.isFunctionExpression(functionNode)) {
        if (functionNode.name) {
            return functionNode.name.text;
        }

        const parent = functionNode.parent;

        if (ts.isVariableDeclaration(parent)) {
            return getBindingNameText(parent.name);
        }

        if (ts.isPropertyDeclaration(parent) || ts.isPropertyAssignment(parent)) {
            return getPropertyNameText(parent.name);
        }
    }

    return null;
}

/**
 * Resolves text for a binding name when it is a simple identifier.
 *
 * @private function of analyzeSourceFileForRefactorCandidate
 */
function getBindingNameText(name: TypescriptModule.BindingName): string | null {
    const ts = getLoadedTypescriptModule();

    return ts.isIdentifier(name) ? name.text : null;
}

/**
 * Resolves text for a property name while preserving computed names when necessary.
 *
 * @private function of analyzeSourceFileForRefactorCandidate
 */
function getPropertyNameText(name: TypescriptModule.PropertyName): string {
    const ts = getLoadedTypescriptModule();

    if (ts.isIdentifier(name) || ts.isPrivateIdentifier(name) || ts.isStringLiteral(name) || ts.isNumericLiteral(name)) {
        return name.text;
    }

    return name.getText();
}

/**
 * Formats the reason emitted when a function in the file exceeds the complexity threshold.
 *
 * @private function of analyzeSourceFileForRefactorCandidate
 */
function buildComplexityReason(
    structureSummary: Pick<SourceFileStructureSummary, 'maxFunctionComplexity' | 'mostComplexFunctionName'>,
    maxAllowedFunctionComplexity: number,
): string {
    const functionSuffix = structureSummary.mostComplexFunctionName
        ? ` in \`${structureSummary.mostComplexFunctionName}\``
        : '';

    return `complexity ${structureSummary.maxFunctionComplexity}/${maxAllowedFunctionComplexity}${functionSuffix}`;
}

/**
 * Resolves the script kind for a source file extension.
 *
 * @private function of analyzeSourceFileForRefactorCandidate
 */
function getScriptKindForExtension(extension: string): TypescriptModule.ScriptKind {
    const ts = getLoadedTypescriptModule();

    if (extension === '.tsx') {
        return ts.ScriptKind.TSX;
    }

    if (extension === '.jsx') {
        return ts.ScriptKind.JSX;
    }

    if (extension === '.js') {
        return ts.ScriptKind.JS;
    }

    return ts.ScriptKind.TS;
}

/**
 * Normalizes an absolute path for consistent comparisons.
 *
 * @private function of analyzeSourceFileForRefactorCandidate
 */
function normalizeAbsolutePath(pathValue: string): string {
    const normalized = resolve(pathValue);
    return process.platform === 'win32' ? normalized.toLowerCase() : normalized;
}

// Note: [🟡] Code for repository script [analyzeSourceFileForRefactorCandidate](scripts/find-refactor-candidates/analyzeSourceFileForRefactorCandidate.ts) should never be published outside of `@promptbook/cli`
