/**
 * @jest-environment jsdom
 */

import type { ChatMessage } from '../types/ChatMessage';
import type { string_date_iso8601 } from '../../../types/typeAliases';
import { ChatPersistence } from './ChatPersistence';

/**
 * Persistence key used by ChatPersistence unit tests.
 */
const TEST_PERSISTENCE_KEY = 'chat-persistence-test';

/**
 * Storage key generated by ChatPersistence for the test persistence key.
 */
const TEST_STORAGE_KEY = `promptbook_chat_${TEST_PERSISTENCE_KEY}`;

/**
 * Stable chat message fixture used across persistence tests.
 */
const TEST_MESSAGES: Array<ChatMessage> = [
    {
        id: 'message-1',
        sender: 'USER',
        content: 'Hello from persisted chat',
        createdAt: '2026-03-10T12:00:00Z' as string_date_iso8601,
        isComplete: true,
    },
];

describe('ChatPersistence', () => {
    beforeEach(() => {
        jest.restoreAllMocks();
        ChatPersistence.clearMessages(TEST_PERSISTENCE_KEY);
    });

    afterEach(() => {
        ChatPersistence.clearMessages(TEST_PERSISTENCE_KEY);
    });

    it('loads saved messages from localStorage when storage works', () => {
        ChatPersistence.saveMessages(TEST_PERSISTENCE_KEY, TEST_MESSAGES);

        expect(localStorage.getItem(TEST_STORAGE_KEY)).not.toBeNull();
        expect(ChatPersistence.loadMessages(TEST_PERSISTENCE_KEY)).toEqual(TEST_MESSAGES);
    });

    it('falls back to in-memory storage when localStorage throws', () => {
        const warnSpy = jest.spyOn(console, 'warn').mockImplementation(() => {});
        const setItemSpy = jest.spyOn(Storage.prototype, 'setItem').mockImplementation(() => {
            throw new Error('Storage quota exceeded');
        });

        ChatPersistence.saveMessages(TEST_PERSISTENCE_KEY, TEST_MESSAGES);
        expect(setItemSpy).toHaveBeenCalled();

        const getItemSpy = jest.spyOn(Storage.prototype, 'getItem').mockImplementation(() => {
            throw new Error('Storage is unavailable');
        });

        expect(ChatPersistence.loadMessages(TEST_PERSISTENCE_KEY)).toEqual(TEST_MESSAGES);
        expect(getItemSpy).toHaveBeenCalled();

        const removeItemSpy = jest.spyOn(Storage.prototype, 'removeItem').mockImplementation(() => {
            throw new Error('Storage is unavailable');
        });

        ChatPersistence.clearMessages(TEST_PERSISTENCE_KEY);
        expect(removeItemSpy).toHaveBeenCalled();
        expect(ChatPersistence.loadMessages(TEST_PERSISTENCE_KEY)).toEqual([]);
        expect(warnSpy).toHaveBeenCalled();
    });
});
