/**
 * Generates Promptbook branding header for exported files
 *
 * @private utility of `<Chat/>` component
 */
export function getPromptbookBranding(shareUrl: string): string {
    const timestamp = new Date().toLocaleString();
    return `Generated by Promptbook Studio - ${timestamp}\nShare link: ${shareUrl}\nhttps://promptbook.studio\n\n`;
}
