import { spaceTrim } from 'spacetrim';
import type { AgentModelRequirements } from '../../book-2.0/agent-source/AgentModelRequirements';
import { TODO_USE } from '../../utils/organization/TODO_USE';
import { BaseCommitmentDefinition } from '../_base/BaseCommitmentDefinition';

/**
 * MESSAGE SUFFIX commitment definition
 *
 * The MESSAGE SUFFIX commitment stores a hardcoded message that is appended
 * to every assistant response in Agents Server runtimes.
 *
 * Example usage in agent source:
 *
 * ```book
 * MESSAGE SUFFIX This message was generated by Promptbook.
 * ```
 *
 * @private [🪔] Maybe export the commitments through some package
 */
export class MessageSuffixCommitmentDefinition extends BaseCommitmentDefinition<'MESSAGE SUFFIX'> {
    public constructor() {
        super('MESSAGE SUFFIX');
    }

    /**
     * Short one-line description of MESSAGE SUFFIX.
     */
    get description(): string {
        return 'Set a hardcoded suffix appended to every assistant response.';
    }

    /**
     * Icon for this commitment.
     */
    get icon(): string {
        return '🏷️';
    }

    /**
     * Markdown documentation for MESSAGE SUFFIX commitment.
     */
    get documentation(): string {
        return spaceTrim(`
            # MESSAGE SUFFIX

            Defines a hardcoded message appended to every assistant response.

            ## Key aspects

            - Does not modify the system message or model requirements.
            - Supports multiline markdown content.
            - Useful for branding, legal notes, and disclosure notices.
            - If multiple \`MESSAGE SUFFIX\` commitments are present, the last one takes precedence.

            ## Example

            \`\`\`book
            Branded Assistant

            MESSAGE SUFFIX
            This was generated by Promptbook, the best tool to create AI agents.
            \`\`\`
        `);
    }

    applyToAgentModelRequirements(requirements: AgentModelRequirements, content: string): AgentModelRequirements {
        TODO_USE(content);

        // MESSAGE SUFFIX does not modify model requirements.
        // It is consumed by parsing/runtime layers in Agents Server.
        return requirements;
    }
}

/**
 * Note: [💞] Ignore a discrepancy between file name and entity name
 */
