import colors from 'colors';
import type { Command } from 'commander';
import { writeFile } from 'fs/promises';
import { join } from 'path';
import spaceTrim from 'spacetrim';
import { createLibraryFromDirectory } from '../../library/constructors/createLibraryFromDirectory';
import { libraryToJson } from '../../library/libraryToJson';
import type { string_file_extension } from '../../types/typeAliases';

/**
 * Initializes `make` command for Promptbook CLI utilities
 *
 * @private part of `promptbookCli`
 */
export function initializeMake(program: Command) {
    const helloCommand = program.command('make');
    helloCommand.description(
        spaceTrim(`
            Makes a new promptbook library in given folder
      `),
    );

    helloCommand.argument('<path>', 'Path to promptbook directory');
    helloCommand.option('--project-name', `Name of the project for whom library is`, 'Project');
    helloCommand.option(
        '-f, --format <format>',
        spaceTrim(`
            Output format of builded library "javascript", "typescript" or "json"

            Note: You can use multiple formats separated by comma
        `),
        'javascript' /* <- Note: [🏳‍🌈] */,
    );
    helloCommand.option('--no-validation', `Do not validate logic of promptbooks in library`, true);
    helloCommand.option(
        '--validation',
        `Types of validations separated by comma (options "logic","imports")`,
        'logic,imports',
    );

    // TODO: !!! Auto-detect AI api keys + explicit api keys as argv

    helloCommand.action(async (path, { projectName, format, validation }) => {
        console.info('!!!', { projectName, path, format, validation });

        const library = await createLibraryFromDirectory(path, {
            isVerbose: true,
            isRecursive: true,
        });

        // TODO: !!! Validate logic

        const libraryJson = await libraryToJson(library);
        const libraryJsonString = JSON.stringify(libraryJson);

        const saveFile = async (extension: string_file_extension, content: string) => {
            const filePath = join(path, `promptbook-library.${extension}`);
            await writeFile(filePath, content, 'utf-8');
            console.info(colors.green(`Maked ${filePath}`));
        };

        if (format.includes('json')) {
            await saveFile('json', libraryJsonString + '\n');
        }

        if (format.includes('javascript')) {
            // TODO: !!!!;
            // TODO: !!! DRY javascript and typescript
            format.push('javascript');
        }

        if (format.includes('typescript')) {
            // TODO: !!!!!!!! Javascript json
            await saveFile(
                'ts',
                spaceTrim(
                    `
                        import type { PromptbookLibrary, SimplePromptbookLibrary } from '@promptbook/types';
                        import type { PromptbookLibrary } from '@promptbook/core';

                        /**
                         * Promptbook library for ${projectName}
                         *
                         * @private internal cache for \`getPromptbookLibrary\`
                         */
                        let promptbookLibrary: null | SimplePromptbookLibrary = null;


                        /**
                         *  Get promptbook library for ${projectName}
                         *
                         *  @returns {PromptbookLibrary} Library of promptbooks for ${projectName}
                         *  @generated by \`@promptbook/cli\`
                         */
                        export function getPromptbookLibrary(): PromptbookLibrary{
                            if(promptbookLibrary===null){
                                promptbookLibrary = createLibraryFromJson(...${libraryJsonString});
                            }

                            return promptbookLibrary;
                        }
                    ` + '\n',
                ),
            );
        }

        process.exit(0);
    });
}
