import { capitalize } from '../normalization/capitalize';
import { computeHash } from './computeHash';

/**
 * Creates a human-readable hash as a short, story-like phrase.
 *
 * @param wordCount how many words to include (defaults to {@link DEFAULT_LINGUISTIC_HASH_WORD_COUNT}, clamped to
 * {@link MIN_LINGUISTIC_HASH_WORD_COUNT}..{@link MAX_LINGUISTIC_HASH_WORD_COUNT})
 *
 * @public exported from `@promptbook/utils`
 */
export async function linguisticHash(input: string, wordCount?: number): Promise<string> {
    const hash: string = computeHash(input);
    const normalizedWordCount = normalizeLinguisticHashWordCount(wordCount);
    const words = createLinguisticHashWords(hash, normalizedWordCount);

    return capitalize(words.join(' '));
}

const HASH_SEGMENT_LENGTH = 8;

/**
 * The minimum number of words for a linguistic hash.
 */
export const MIN_LINGUISTIC_HASH_WORD_COUNT = 1;

/**
 * The default number of words for a linguistic hash.
 */
export const DEFAULT_LINGUISTIC_HASH_WORD_COUNT = 7;

/**
 * Extracts a deterministic numeric seed from a SHA-256 hash.
 */
function getHashSeed(hash: string, segmentIndex: number): number {
    const expandedHash: string = `${hash}${hash}`;
    const start: number = (segmentIndex * HASH_SEGMENT_LENGTH + segmentIndex) % hash.length;
    return parseInt(expandedHash.substring(start, start + HASH_SEGMENT_LENGTH), 16);
}

/**
 * Picks a deterministic item from a list based on the hash seed.
 */
function pickFromHash<T>(hash: string, segmentIndex: number, list: readonly T[]): T {
    const seed = getHashSeed(hash, segmentIndex);
    return list[seed % list.length]!;
}

/**
 * Types of words used in linguistic hash output.
 */
type LinguisticWordKind = 'adjective' | 'noun' | 'verb';

/**
 * Ordered word kinds used to build the linguistic hash output.
 */
const WORD_SEQUENCE: LinguisticWordKind[] = [
    'adjective',
    'noun',
    'verb',
    'adjective',
    'noun',
    'verb',
    'adjective',
    'noun',
    'verb',
    'adjective',
    'noun',
    'verb',
    'adjective',
    'noun',
    'verb',
    'adjective',
    'noun',
    'verb',
    'adjective',
    'noun',
];

/**
 * The maximum number of words for a linguistic hash.
 */
export const MAX_LINGUISTIC_HASH_WORD_COUNT = WORD_SEQUENCE.length;

/**
 * Index of the noun used for single-word hashes.
 */
const SINGLE_WORD_INDEX = 1;

/**
 * Normalizes the word count to a supported integer range.
 */
export function normalizeLinguisticHashWordCount(wordCount?: number | null): number {
    if (typeof wordCount !== 'number' || !Number.isFinite(wordCount)) {
        return DEFAULT_LINGUISTIC_HASH_WORD_COUNT;
    }

    const rounded = Math.round(wordCount);
    return Math.min(MAX_LINGUISTIC_HASH_WORD_COUNT, Math.max(MIN_LINGUISTIC_HASH_WORD_COUNT, rounded));
}

/**
 * Picks a deterministic word from the hash by kind.
 */
function pickWordFromHash(hash: string, segmentIndex: number, wordKind: LinguisticWordKind): string {
    return pickFromHash(hash, segmentIndex, WORD_LISTS[wordKind]);
}

/**
 * Creates the deterministic word sequence used for the linguistic hash output.
 */
function createLinguisticHashWordSequence(hash: string): string[] {
    return WORD_SEQUENCE.map((wordKind, index) => pickWordFromHash(hash, index, wordKind));
}

/**
 * Selects the requested number of words from the hash output.
 */
function createLinguisticHashWords(hash: string, wordCount: number): string[] {
    const words = createLinguisticHashWordSequence(hash);

    if (wordCount === 1) {
        return [words[SINGLE_WORD_INDEX]!];
    }

    return words.slice(0, wordCount);
}

const ADJECTIVES = [
    'red',
    'blue',
    'green',
    'yellow',
    'quick',
    'slow',
    'bright',
    'dark',
    'happy',
    'sad',
    'brave',
    'calm',
    'clever',
    'eager',
    'fancy',
    'grand',
    'jolly',
    'kind',
    'lucky',
    'nice',
    'proud',
    'silly',
    'wise',
    'young',
    'old',
    'big',
    'small',
    'fast',
    'shiny',
    'wild',
    'silent',
    'loud',
    'soft',
    'hard',
    'warm',
    'cold',
    'sweet',
    'sour',
    'bitter',
    'salty',
    'rich',
    'poor',
    'heavy',
    'light',
    'strong',
    'weak',
    'smooth',
    'rough',
    'clean',
    'dirty',
    'fresh',
    'stale',
    'sharp',
    'blunt',
    'thick',
    'thin',
    'wide',
    'narrow',
    'deep',
    'shallow',
    'mighty',
    'gentle',
    'fierce',
    'vibrant',
    'dusty',
    'golden',
    'silver',
    'frozen',
    'burning',
    'ancient',
    'modern',
    'hidden',
    'lost',
    'found',
    'magic',
    'mystic',
    'cosmic',
    'stellar',
    'lunar',
    'solar',
    'misty',
    'foggy',
    'stormy',
    'sunny',
    'windy',
    'quiet',
    'noisy',
    'peaceful',
    'busy',
    'empty',
    'full',
    'round',
    'square',
    'flat',
    'curved',
    'tiny',
    'huge',
    'giant',
    'little',
    'short',
    'long',
    'near',
    'distant',
    'inner',
    'outer',
    'patient',
    'steady',
    'noble',
    'pure',
    'graceful',
    'honest',
    'simple',
    'complex',
    'active',
    'passive',
    'vivid',
    'pale',
    'loyal',
    'true',
    'false',
    'fair',
    'clear',
    'murky',
    'vast',
    'slick',
    'slippery',
    'sticky',
    'dull',
    'keen',
    'broad',
    'slim',
    'slender',
    'fat',
    'lean',
    'stiff',
    'flexible',
    'rigid',
    'elastic',
    'tough',
    'brittle',
    'fragile',
    'solid',
    'liquid',
    'gaseous',
    'airy',
    'weighty',
    'buoyant',
    'dense',
    'sparse',
    'hollow',
    'stuffed',
    'crowded',
    'lonely',
    'social',
    'private',
    'public',
    'secret',
    'famous',
    'certain',
    'vague',
    'plain',
    'easy',
    'tame',
    'mild',
    'hot',
    'cool',
    'dry',
    'wet',
    'damp',
    'moist',
    'soaked',
    'parched',
    'hungry',
    'thirsty',
    'sleepy',
    'awake',
    'tired',
    'lazy',
    'idle',
    'swift',
    'rapid',
    'unstable',
    'shaky',
    'firm',
    'bold',
    'timid',
    'brave',
    'cowardly',
    'smart',
    'dumb',
    'foolish',
    'mean',
    'rude',
    'tasty',
    'bland',
    'arctic',
    'tropical',
    'deserted',
    'urban',
    'rural',
    'local',
    'global',
    'digital',
    'analog',
    'virtual',
    'real',
    'fake',
    'natural',
    'artificial',
    'living',
    'dead',
    'broken',
    'fixed',
    'new',
    'worn',
    'neat',
    'messy',
    'brave',
    'fearful',
    'proud',
    'humble',
    'greedy',
    'generous',
    'calm',
    'angry',
    'happy',
    'sad',
    'excited',
    'bored',
    'strange',
    'normal',
    'odd',
    'even',
    'rare',
    'common',
    'unique',
    'plain',
    'fancy',
    'basic',
    'prime',
    'super',
    'mega',
    'ultra',
    'micro',
    'nano',
    'macro',
    'mini',
];

const NOUNS = [
    'apple',
    'sky',
    'tree',
    'fox',
    'cat',
    'bird',
    'dog',
    'river',
    'mountain',
    'forest',
    'ocean',
    'star',
    'moon',
    'sun',
    'cloud',
    'flower',
    'leaf',
    'stone',
    'wind',
    'rain',
    'fire',
    'ice',
    'book',
    'dream',
    'song',
    'road',
    'gate',
    'key',
    'lamp',
    'map',
    'house',
    'city',
    'bridge',
    'field',
    'garden',
    'lake',
    'beach',
    'island',
    'valley',
    'desert',
    'world',
    'spirit',
    'heart',
    'mind',
    'soul',
    'life',
    'time',
    'space',
    'light',
    'shadow',
    'sound',
    'music',
    'voice',
    'word',
    'page',
    'story',
    'pearl',
    'gold',
    'silver',
    'crystal',
    'diamond',
    'emerald',
    'ruby',
    'path',
    'trail',
    'peak',
    'shore',
    'wave',
    'tide',
    'flame',
    'spark',
    'beam',
    'ray',
    'seed',
    'root',
    'branch',
    'bloom',
    'thorn',
    'bark',
    'shell',
    'feather',
    'wing',
    'claw',
    'paw',
    'nest',
    'cave',
    'grove',
    'tower',
    'castle',
    'crown',
    'sword',
    'shield',
    'coin',
    'gem',
    'ring',
    'bell',
    'clock',
    'compass',
    'anchor',
    'torch',
    'flute',
    'harp',
    'drum',
    'lens',
    'glass',
    'sand',
    'dust',
    'mist',
    'dew',
    'dawn',
    'dusk',
    'night',
    'day',
    'year',
    'age',
    'bolt',
    'drop',
    'storm',
    'snow',
    'hail',
    'fog',
    'smoke',
    'vapor',
    'gas',
    'fluid',
    'liquid',
    'solid',
    'metal',
    'rock',
    'dirt',
    'clay',
    'sand',
    'salt',
    'sugar',
    'wood',
    'bone',
    'skin',
    'flesh',
    'blood',
    'cell',
    'atom',
    'pulse',
    'beat',
    'breath',
    'sigh',
    'name',
    'echo',
    'image',
    'vision',
    'thought',
    'idea',
    'plan',
    'goal',
    'wish',
    'hope',
    'fear',
    'joy',
    'love',
    'hate',
    'will',
    'power',
    'force',
    'energy',
    'motion',
    'speed',
    'place',
    'point',
    'line',
    'shape',
    'form',
    'size',
    'mass',
    'weight',
    'heat',
    'cold',
    'color',
    'tone',
    'pitch',
    'rhythm',
    'vibe',
    'mood',
    'state',
    'way',
    'step',
    'move',
    'turn',
    'fall',
    'rise',
    'jump',
    'leap',
    'run',
    'walk',
    'rest',
    'stay',
    'trip',
    'quest',
    'task',
    'work',
    'job',
    'play',
    'game',
    'sport',
    'art',
    'craft',
    'tool',
    'ship',
    'boat',
    'car',
    'bike',
    'train',
    'plane',
    'hub',
    'base',
    'core',
    'node',
    'link',
    'net',
    'web',
    'box',
    'bag',
    'jar',
    'cup',
    'bowl',
    'plate',
    'dish',
    'spoon',
    'fork',
    'knife',
    'pan',
    'pot',
    'bed',
    'desk',
    'chair',
    'door',
    'wall',
    'roof',
    'floor',
];

const VERBS = [
    'jumping',
    'dancing',
    'flying',
    'running',
    'singing',
    'shining',
    'growing',
    'flowing',
    'falling',
    'rising',
    'sleeping',
    'walking',
    'talking',
    'thinking',
    'dreaming',
    'looking',
    'feeling',
    'smiling',
    'laughing',
    'playing',
    'working',
    'resting',
    'moving',
    'staying',
    'beaming',
    'glowing',
    'sparkling',
    'waiting',
    'waking',
    'drifting',
    'spinning',
    'gliding',
    'soaring',
    'floating',
    'whispering',
    'calling',
    'seeking',
    'finding',
    'giving',
    'taking',
    'weaving',
    'building',
    'creating',
    'burning',
    'freezing',
    'melting',
    'breathing',
    'pulsing',
    'beating',
    'living',
    'learning',
    'knowing',
    'hidden',
    'shown',
    'broken',
    'mended',
    'lost',
    'found',
    'starting',
    'ending',
    'climbing',
    'diving',
    'swimming',
    'sailing',
    'rolling',
    'shaking',
    'turning',
    'shifting',
    'changing',
    'fading',
    'dying',
    'born',
    'humming',
    'crying',
    'racing',
    'creeping',
    'hiding',
    'watching',
    'hearing',
    'sensing',
    'longing',
    'hoping',
    'loving',
    'fearing',
    'wondering',
    'wandering',
    'traveling',
    'crossing',
    'meeting',
    'parting',
    'keeping',
    'sharing',
    'sparking',
    'flaming',
    'healing',
    'solving',
    'opening',
    'closing',
    'lifting',
    'pulling',
    'pushing',
    'holding',
    'tossing',
    'throwing',
    'catching',
    'fixing',
    'making',
    'doing',
    'seeing',
    'tasting',
    'smelling',
    'touching',
    'pacing',
    'hurrying',
    'pausing',
    'going',
    'coming',
    'leaving',
    'acting',
    'being',
    'seeming',
    'shrinking',
    'widening',
    'narrowing',
    'heating',
    'cooling',
    'drying',
    'wetting',
    'filling',
    'filling',
    'emptying',
    'letting',
    'gaining',
    'winning',
    'failing',
    'trying',
    'using',
    'getting',
    'showing',
    'hiding',
    'breaking',
    'fixing',
    'saving',
    'spending',
    'buying',
    'selling',
    'paying',
    'costing',
    'reaching',
    'missing',
    'hitting',
    'striking',
    'leading',
    'following',
    'helping',
    'serving',
    'teaching',
    'training',
    'coding',
    'writing',
    'reading',
    'drawing',
    'painting',
    'crafting',
    'shaping',
    'forming',
    'joining',
    'splitting',
    'sharing',
    'bonding',
    'healing',
    'harming',
    'protecting',
    'fighting',
    'defending',
    'attacking',
    'escaping',
    'catching',
    'trapping',
    'freeing',
    'binding',
    'weaving',
    'spinning',
];

/**
 * Maps each word kind to its source list.
 */
const WORD_LISTS: Record<LinguisticWordKind, readonly string[]> = {
    adjective: ADJECTIVES,
    noun: NOUNS,
    verb: VERBS,
};

/**
 * TODO: Prompt: Extract number constants and word list to a separate file for reuse.
 */
