import { describe, expect, it } from '@jest/globals';
import { createDnsZoneFileExport } from './createDnsZoneFileExport';

describe('createDnsZoneFileExport', () => {
    it('exports every record as one importable zone file', () => {
        const zoneFile = createDnsZoneFileExport({
            domain: 'example.com',
            records: [
                { type: 'A', name: 'mail.example.com', value: '203.0.113.42', note: null },
                { type: 'MX', name: 'example.com', value: '10 mail.example.com.', note: null },
                { type: 'TXT', name: 'example.com', value: 'v=spf1 mx -all', note: null },
                { type: 'CAA', name: 'example.com', value: '0 issue "letsencrypt.org"', note: null },
            ],
        });

        expect(zoneFile).toContain('; DNS records for example.com generated by the Promptbook Agents Server');
        expect(zoneFile).toContain('mail.example.com.\t1\tIN\tA\t203.0.113.42');
        expect(zoneFile).toContain('example.com.\t1\tIN\tMX\t10 mail.example.com.');
        expect(zoneFile).toContain('example.com.\t1\tIN\tTXT\t"v=spf1 mx -all"');
        expect(zoneFile).toContain('example.com.\t1\tIN\tCAA\t0 issue "letsencrypt.org"');
    });

    it('writes hostname targets as absolute names', () => {
        const zoneFile = createDnsZoneFileExport({
            domain: 'agents.example.com',
            records: [{ type: 'CNAME', name: 'agents.example.com', value: 'live.example.com', note: null }],
        });

        expect(zoneFile).toContain('agents.example.com.\t1\tIN\tCNAME\tlive.example.com.');
    });

    it('splits long text values into zone file character strings', () => {
        const longDkimKey = `v=DKIM1; k=rsa; p=${'A'.repeat(300)}`;
        const zoneFile = createDnsZoneFileExport({
            domain: 'example.com',
            records: [{ type: 'TXT', name: 'ptbk._domainkey.example.com', value: longDkimKey, note: null }],
        });
        const textChunks = zoneFile.match(/"[^"]*"/g) || [];

        expect(textChunks).toHaveLength(2);
        expect(textChunks.map((textChunk) => textChunk.slice(1, -1)).join('')).toBe(longDkimKey);
    });
});
