import { spaceTrim } from 'spacetrim';
import { CLOUDFLARE_DNS_RECORD_TTL_AUTOMATIC } from '../cloudflare/CloudflareApi';
import type { DnsRecordInstruction } from './DnsRecordInstruction';

/**
 * DNS record types whose value is a hostname which has to be absolute in a zone file.
 */
const DNS_ZONE_FILE_HOSTNAME_RECORD_TYPES: ReadonlySet<string> = new Set(['CNAME', 'NS', 'PTR']);

/**
 * A zone-file character string can hold at most 255 characters, longer `TXT` values are split into more strings.
 */
const DNS_ZONE_FILE_TEXT_CHUNK_LENGTH = 255;

/**
 * Creates a BIND zone file with all given DNS records.
 *
 * The file can be imported at once by DNS providers which support zone-file imports, so that an administrator does
 * not have to retype the records one by one.
 *
 * @param options - Domain and the records which should be part of the export.
 * @returns BIND zone file contents.
 */
export function createDnsZoneFileExport(options: {
    readonly domain: string;
    readonly records: ReadonlyArray<DnsRecordInstruction>;
}): string {
    const recordLines = options.records.map((record) =>
        [
            `${normalizeZoneFileRecordName(record.name)}.`,
            String(CLOUDFLARE_DNS_RECORD_TTL_AUTOMATIC),
            'IN',
            record.type.toUpperCase(),
            createZoneFileRecordData(record.type, record.value),
        ].join('\t'),
    );

    return spaceTrim(
        (block) => `
            ; DNS records for ${options.domain} generated by the Promptbook Agents Server
            ; Import this file at your DNS provider instead of adding every record by hand.

            ${block(recordLines.join('\n'))}
        `,
    );
}

/**
 * Normalizes one record name into its absolute zone-file form without the trailing dot.
 *
 * @param name - Fully qualified DNS record name.
 * @returns Record name usable in a zone file.
 */
function normalizeZoneFileRecordName(name: string): string {
    return name.trim().toLowerCase().replace(/\.$/, '');
}

/**
 * Creates the zone-file record data of one DNS record.
 *
 * @param type - DNS record type.
 * @param value - DNS record value as shown in the DNS manual.
 * @returns Record data in the zone-file syntax.
 */
function createZoneFileRecordData(type: string, value: string): string {
    const normalizedType = type.toUpperCase();
    const normalizedValue = value.trim();

    if (normalizedType === 'TXT') {
        return createZoneFileTextRecordData(normalizedValue);
    }

    if (DNS_ZONE_FILE_HOSTNAME_RECORD_TYPES.has(normalizedType)) {
        return normalizedValue.endsWith('.') ? normalizedValue : `${normalizedValue}.`;
    }

    return normalizedValue;
}

/**
 * Quotes one `TXT` value and splits it into zone-file character strings.
 *
 * @param value - Raw text value, for example an SPF or DMARC policy.
 * @returns Quoted character strings.
 */
function createZoneFileTextRecordData(value: string): string {
    const unquotedValue = value.replace(/^"(.*)"$/s, '$1');
    const textChunks = unquotedValue.match(new RegExp(`.{1,${DNS_ZONE_FILE_TEXT_CHUNK_LENGTH}}`, 'gs')) || [''];

    return textChunks.map((textChunk) => `"${textChunk.replace(/"/g, '\\"')}"`).join(' ');
}
