import type { CsvSettings } from './formats/csv/CsvSettings';
import { just } from './utils/organization/just';
import { $asDeeplyFrozenSerializableJson } from './utils/serialization/$asDeeplyFrozenSerializableJson';

/**
 * Warning message for the generated sections and files files
 *
 * @private within the repository
 */
export const GENERATOR_WARNING = `⚠️ WARNING: This code has been generated so that any manual changes will be overwritten`;

/**
 * Claim for the Promptbook
 *
 * TODO: [🗽] Unite branding and make single place for it
 *
 * @public exported from `@promptbook/core`
 */
export const CLAIM = `Supercharge LLM models with Promptbook`;

/**
 * Warning message for the generated sections and files files
 *
 * @private within the repository
 */
export const GENERATOR_WARNING_BY_PROMPTBOOK_CLI = `⚠️ WARNING: This code has been generated by \`@promptbook/cli\` so that any manual changes will be overwritten`;

// <- TODO: [🧠] Better system for generator warnings - not always "code" and "by `@promptbook/cli`"

/**
 * The maximum number of iterations for a loops
 *
 * @private within the repository - too low-level in comparison with other `MAX_...`
 */
export const LOOP_LIMIT = 1000;

/**
 * The maximum number of iterations for a loops which adds characters one by one
 *
 * @private within the repository - too low-level in comparison with other `MAX_...`
 */
export const CHARACTER_LOOP_LIMIT = 100000;

/**
 * Timeout for the connections in milliseconds
 *
 * @private within the repository - too low-level in comparison with other `MAX_...`
 */
export const CONNECTION_TIMEOUT_MS = 7 * 1000;

/**
 * How many times to retry the connections
 *
 * @private within the repository - too low-level in comparison with other `MAX_...`
 */
export const CONNECTION_RETRIES_LIMIT = 5;

/**
 * Short time interval to prevent race conditions in milliseconds
 *
 * @private within the repository - too low-level in comparison with other `MAX_...`
 */
export const IMMEDIATE_TIME = 10;

/**
 * The maximum number of (LLM) tasks running in parallel
 *
 * @public exported from `@promptbook/core`
 */
export const MAX_PARALLEL_COUNT = 5; // <- TODO: [🤹‍♂️]

/**
 * The maximum number of attempts to execute LLM task before giving up
 *
 * @public exported from `@promptbook/core`
 */
export const MAX_EXECUTION_ATTEMPTS = 3; // <- TODO: [🤹‍♂️]

/**
 * The maximum length of the (generated) filename
 *
 * @public exported from `@promptbook/core`
 */
export const MAX_FILENAME_LENGTH = 30;

/**
 * @@@
 * TODO: [🐝][main] !!! Use
 *
 * @public exported from `@promptbook/core`
 */
export const MAX_KNOWLEDGE_SOURCES_SCRAPING_DEPTH = 3;

/**
 * @@@
 * TODO: [🐝][main] !!! Use
 *
 * @public exported from `@promptbook/core`
 */
export const MAX_KNOWLEDGE_SOURCES_SCRAPING_TOTAL = 200;

/**
 * Where to store the cache of executions for promptbook CLI
 * 
 * Note: When the folder does not exist, it is created recursively
 *
 * @public exported from `@promptbook/core`
 */
export const EXECUTIONS_CACHE_DIRNAME = '/.promptbook/executions-cache';

/**
 * Where to store the scrape cache
 * 
 * Note: When the folder does not exist, it is created recursively
 *
 * @public exported from `@promptbook/core`
 */
export const SCRAPE_CACHE_DIRNAME = '/.promptbook/scrape-cache';

/**
 * The name of the builded pipeline collection made by CLI `ptbk make` and for lookup in `createCollectionFromDirectory`
 *
 * @public exported from `@promptbook/core`
 */
export const PIPELINE_COLLECTION_BASE_FILENAME = `index`;

/**
 * Nonce which is used for replacing things in strings
 *
 * @private within the repository
 */
export const REPLACING_NONCE = 'u$k42k%!V2zo34w7Fu#@QUHYPW';

/**
 * The names of the parameters that are reserved for special purposes
 *
 * @public exported from `@promptbook/core`
 */
export const RESERVED_PARAMETER_NAMES = $asDeeplyFrozenSerializableJson('RESERVED_PARAMETER_NAMES', [
    'content',
    'context', // <- [🧠][🏍] Is parameter {context} good for anything?
    'knowledge',
    'samples',
    'modelName',
    'currentDate',

    // <- TODO: !!!!! list here all command names
    // <- TODO: Add more like 'date', 'modelName',...
    // <- TODO: Add [emoji] + instructions ACRY when adding new reserved parameter
] as const);

/**
 * @@@
 *
 * @private within the repository
 */
export const RESERVED_PARAMETER_MISSING_VALUE = 'MISSING-' + REPLACING_NONCE;

/**
 * @@@
 *
 * @private within the repository
 */
export const RESERVED_PARAMETER_RESTRICTED = 'RESTRICTED-' + REPLACING_NONCE;

/**
 * The thresholds for the relative time in the `moment` NPM package.
 *
 * @see https://momentjscom.readthedocs.io/en/latest/moment/07-customization/13-relative-time-threshold/
 * @private within the repository - too low-level in comparison with other constants
 */
export const MOMENT_ARG_THRESHOLDS = {
    ss: 3, // <- least number of seconds to be counted in seconds, minus 1. Must be set after setting the `s` unit or without setting the `s` unit.
} as const;

/**
 * @@@
 *
 * @public exported from `@promptbook/core`
 */
export const DEFAULT_REMOTE_URL = 'https://api.pavolhejny.com/';

/**
 * @@@
 *
 * @public exported from `@promptbook/core`
 */
export const DEFAULT_REMOTE_URL_PATH = '/promptbook/socket.io';

// <- TODO: [🧜‍♂️]

/**
 * @@@
 *
 * @public exported from `@promptbook/core`
 */
export const DEFAULT_CSV_SETTINGS: CsvSettings = Object.freeze({
    delimiter: ',',
    quoteChar: '"',
    newline: '\n',
    skipEmptyLines: true,
});

/**
 * @@@
 *
 * @public exported from `@promptbook/core`
 */
export const IS_VERBOSE = false;

/**
 * @@@
 *
 * @private within the repository
 */
export const IS_PIPELINE_LOGIC_VALIDATED: boolean = just(
    /**/
    // Note: In normal situations, we check the pipeline logic:
    true,
    /**/

    /*/
    // When working on some new features, you can temporarily turn off the validation:
    false,
    /**/

    // Commit message:
    // [🔑] Temporarily **disable** pipeline validation
    // [🔒] **Enable** pipeline validation
);

/**
 * @@@
 *
 * @private within the repository
 */
export const IS_COST_PREVENTED: boolean = just(
    /*/
    // Note: In normal situations, we prevent ability to use real API keys in tests:
    true,
    /**/

    /**/
    // When working on preparations, you can temporarily turn off the prevention:
    false,
    /**/

    // Commit message:
    // [🔑] Temporarily **disable** cost-prevention
    // [🔒] **Enable** cost-prevention
);

/**
 * TODO: [🧠][🧜‍♂️] Maybe join remoteUrl and path into single value
 */
