import fs from 'fs';
import path from 'path';
import { GENERATOR_WARNING } from '../../../../src/config';

/**
 * Constant for app dir.
 */
const appDir = path.join(__dirname, '..', '..', 'src', 'app');
/**
 * Constant for public dir.
 */
const publicDir = path.join(__dirname, '..', '..', 'public');
/**
 * Constant for output file.
 */
const outputFile = path.join(__dirname, '..', '..', 'src', 'generated', 'reservedPaths.ts');

// Read the app directory
/**
 * Constant for app entries.
 */
const appEntries = fs.readdirSync(appDir, { withFileTypes: true });

// Filter to get only directories (excluding dynamic routes like [agentName])
/**
 * Constant for reserved paths.
 */
const reservedPaths = appEntries
    .filter((entry) => entry.isDirectory())
    .map((entry) => entry.name)
    .filter((name) => !name.startsWith('[') && !name.endsWith(']'));

// Read the public directory (files and folders)
/**
 * Constant for public entries.
 */
const publicEntries = fs.readdirSync(publicDir, { withFileTypes: true });
/**
 * Constant for public paths.
 */
const publicPaths = publicEntries.map((entry) => entry.name).filter((name) => !name.startsWith('.'));

// Add additional paths that are not in app or public but should be reserved
/**
 * Collection of additional paths.
 */
const additionalPaths = [
    '_next', // Next.js internal paths
    'manifest.webmanifest', // PWA manifest
];

/**
 * Constant for all reserved paths.
 */
const allReservedPaths = [...new Set([...reservedPaths, ...publicPaths, ...additionalPaths])].sort();

// Generate the TypeScript file
/**
 * Constant for content.
 */
const content = `/**
 * Reserved paths that should not be treated as agent names.
 * This file is auto-generated by scripts/generate-reserved-paths.js
 *
 * ${GENERATOR_WARNING}
 *
 * @see /apps/agents-server/src/app - source directory for routes
 * @see /apps/agents-server/public - source directory for static files
 * @see /apps/agents-server/src/middleware.ts - where this is used
 */
export const RESERVED_PATHS: readonly string[] = ${JSON.stringify(allReservedPaths, null, 4)} as const;
`;

// Ensure the generated directory exists
/**
 * Constant for generated dir.
 */
const generatedDir = path.dirname(outputFile);
if (!fs.existsSync(generatedDir)) {
    fs.mkdirSync(generatedDir, { recursive: true });
}

// Write the file
fs.writeFileSync(outputFile, content, 'utf-8');

console.log(`Generated ${outputFile} with ${allReservedPaths.length} reserved paths:`);
console.log(allReservedPaths.join(', '));
