import fs from 'fs';
import path from 'path';
import { GENERATOR_WARNING } from '../../../../src/config';

const appDir = path.join(__dirname, '..', '..', 'src', 'app');
const publicDir = path.join(__dirname, '..', '..', 'public');
const outputFile = path.join(__dirname, '..', '..', 'src', 'generated', 'reservedPaths.ts');

// Read the app directory
const appEntries = fs.readdirSync(appDir, { withFileTypes: true });

// Filter to get only directories (excluding dynamic routes like [agentName])
const reservedPaths = appEntries
    .filter((entry) => entry.isDirectory())
    .map((entry) => entry.name)
    .filter((name) => !name.startsWith('[') && !name.endsWith(']'));

// Read the public directory (files and folders)
const publicEntries = fs.readdirSync(publicDir, { withFileTypes: true });
const publicPaths = publicEntries.map((entry) => entry.name).filter((name) => !name.startsWith('.'));

// Add additional paths that are not in app or public but should be reserved
const additionalPaths = [
    '_next', // Next.js internal paths
    'manifest.webmanifest', // PWA manifest
];

const allReservedPaths = [...new Set([...reservedPaths, ...publicPaths, ...additionalPaths])].sort();

// Generate the TypeScript file
const content = `/**
 * Reserved paths that should not be treated as agent names.
 * This file is auto-generated by scripts/generate-reserved-paths.js
 *
 * ${GENERATOR_WARNING}
 *
 * @see /apps/agents-server/src/app - source directory for routes
 * @see /apps/agents-server/public - source directory for static files
 * @see /apps/agents-server/src/middleware.ts - where this is used
 */
export const RESERVED_PATHS: readonly string[] = ${JSON.stringify(allReservedPaths, null, 4)} as const;
`;

// Ensure the generated directory exists
const generatedDir = path.dirname(outputFile);
if (!fs.existsSync(generatedDir)) {
    fs.mkdirSync(generatedDir, { recursive: true });
}

// Write the file
fs.writeFileSync(outputFile, content, 'utf-8');

console.log(`Generated ${outputFile} with ${allReservedPaths.length} reserved paths:`);
console.log(allReservedPaths.join(', '));
