'use client';

// ⚠️ WARNING: This code has been generated so that any manual changes will be overwritten
// `@promptbook/components`

import { BOOK_LANGUAGE_VERSION, PROMPTBOOK_ENGINE_VERSION } from '../version';
import type { AvatarChipProps } from '../book-components/AvatarProfile/AvatarChip/AvatarChip';
import { AvatarChip } from '../book-components/AvatarProfile/AvatarChip/AvatarChip';
import type { AvatarChipFromSourceProps } from '../book-components/AvatarProfile/AvatarChip/AvatarChipFromSource';
import { AvatarChipFromSource } from '../book-components/AvatarProfile/AvatarChip/AvatarChipFromSource';
import type { AvatarProfileProps } from '../book-components/AvatarProfile/AvatarProfile/AvatarProfile';
import { AvatarProfile } from '../book-components/AvatarProfile/AvatarProfile/AvatarProfile';
import type { AvatarProfileFromSourceProps } from '../book-components/AvatarProfile/AvatarProfile/AvatarProfileFromSource';
import { AvatarProfileFromSource } from '../book-components/AvatarProfile/AvatarProfile/AvatarProfileFromSource';
import { DEFAULT_BOOK_EDITOR_HEIGHT } from '../book-components/BookEditor/BookEditor';
import type { BookEditorProps } from '../book-components/BookEditor/BookEditor';
import { BookEditor } from '../book-components/BookEditor/BookEditor';
import { AgentChat } from '../book-components/Chat/AgentChat/AgentChat';
import type { AgentChatProps } from '../book-components/Chat/AgentChat/AgentChatProps';
import { Chat } from '../book-components/Chat/Chat/Chat';
import type { ChatProps } from '../book-components/Chat/Chat/ChatProps';
import { useChatAutoScroll } from '../book-components/Chat/hooks/useChatAutoScroll';
import type { SendMessageToLlmChatFunction } from '../book-components/Chat/hooks/useSendMessageToLlmChat';
import { useSendMessageToLlmChat } from '../book-components/Chat/hooks/useSendMessageToLlmChat';
import { LlmChat } from '../book-components/Chat/LlmChat/LlmChat';
import type { LlmChatProps } from '../book-components/Chat/LlmChat/LlmChatProps';
import { MarkdownContent } from '../book-components/Chat/MarkdownContent/MarkdownContent';
import { NORMAL_FLOW } from '../book-components/Chat/MockedChat/constants';
import { FAST_FLOW } from '../book-components/Chat/MockedChat/constants';
import { SLOW_FLOW } from '../book-components/Chat/MockedChat/constants';
import { BLOCKY_FLOW } from '../book-components/Chat/MockedChat/constants';
import { RANDOM_FLOW } from '../book-components/Chat/MockedChat/constants';
import { MOCKED_CHAT_DELAY_CONFIGS } from '../book-components/Chat/MockedChat/constants';
import type { MockedChatDelayConfig } from '../book-components/Chat/MockedChat/MockedChat';
import type { MockedChatProps } from '../book-components/Chat/MockedChat/MockedChat';
import { MockedChat } from '../book-components/Chat/MockedChat/MockedChat';
import type { ChatSaveFormatDefinition } from '../book-components/Chat/save/_common/ChatSaveFormatDefinition';
import { getChatSaveFormatDefinitions } from '../book-components/Chat/save/_common/getChatSaveFormatDefinitions';
import type { string_chat_format_name } from '../book-components/Chat/save/_common/string_chat_format_name';
import { htmlSaveFormatDefinition } from '../book-components/Chat/save/html/htmlSaveFormatDefinition';
import { CHAT_SAVE_FORMATS } from '../book-components/Chat/save/index';
import { jsonSaveFormatDefinition } from '../book-components/Chat/save/json/jsonSaveFormatDefinition';
import { mdSaveFormatDefinition } from '../book-components/Chat/save/markdown/mdSaveFormatDefinition';
import { pdfSaveFormatDefinition } from '../book-components/Chat/save/pdf/pdfSaveFormatDefinition';
import { reactSaveFormatDefinition } from '../book-components/Chat/save/react/reactSaveFormatDefinition';
import { txtSaveFormatDefinition } from '../book-components/Chat/save/text/txtSaveFormatDefinition';
import type { ChatMessage } from '../book-components/Chat/types/ChatMessage';
import type { ChatParticipant } from '../book-components/Chat/types/ChatParticipant';
import type { MessageButton } from '../book-components/Chat/utils/parseMessageButtons';
import { parseMessageButtons } from '../book-components/Chat/utils/parseMessageButtons';
import { ArrowIcon } from '../book-components/icons/ArrowIcon';
import { AttachmentIcon } from '../book-components/icons/AttachmentIcon';
import { MicIcon } from '../book-components/icons/MicIcon';
import { PauseIcon } from '../book-components/icons/PauseIcon';
import { PlayIcon } from '../book-components/icons/PlayIcon';
import { ResetIcon } from '../book-components/icons/ResetIcon';
import { SaveIcon } from '../book-components/icons/SaveIcon';
import { SendIcon } from '../book-components/icons/SendIcon';
import { TemplateIcon } from '../book-components/icons/TemplateIcon';
import { PromptbookAgent } from '../book-components/PromptbookAgent/PromptbookAgent';
import { BrandedQrCode } from '../book-components/Qr/BrandedQrCode';
import { GenericQrCode } from '../book-components/Qr/GenericQrCode';
import { PromptbookQrCode } from '../book-components/Qr/PromptbookQrCode';
import { injectCssModuleIntoShadowRoot } from '../utils/misc/injectCssModuleIntoShadowRoot';
import { AboutPromptbookInformation } from '../utils/misc/xAboutPromptbookInformation';


// Note: Exporting version from each package
export { BOOK_LANGUAGE_VERSION, PROMPTBOOK_ENGINE_VERSION };


// Note: Entities of the `@promptbook/components`
export type { AvatarChipProps };
export { AvatarChip };
export type { AvatarChipFromSourceProps };
export { AvatarChipFromSource };
export type { AvatarProfileProps };
export { AvatarProfile };
export type { AvatarProfileFromSourceProps };
export { AvatarProfileFromSource };
export { DEFAULT_BOOK_EDITOR_HEIGHT };
export type { BookEditorProps };
export { BookEditor };
export { AgentChat };
export type { AgentChatProps };
export { Chat };
export type { ChatProps };
export { useChatAutoScroll };
export type { SendMessageToLlmChatFunction };
export { useSendMessageToLlmChat };
export { LlmChat };
export type { LlmChatProps };
export { MarkdownContent };
export { NORMAL_FLOW };
export { FAST_FLOW };
export { SLOW_FLOW };
export { BLOCKY_FLOW };
export { RANDOM_FLOW };
export { MOCKED_CHAT_DELAY_CONFIGS };
export type { MockedChatDelayConfig };
export type { MockedChatProps };
export { MockedChat };
export type { ChatSaveFormatDefinition };
export { getChatSaveFormatDefinitions };
export type { string_chat_format_name };
export { htmlSaveFormatDefinition };
export { CHAT_SAVE_FORMATS };
export { jsonSaveFormatDefinition };
export { mdSaveFormatDefinition };
export { pdfSaveFormatDefinition };
export { reactSaveFormatDefinition };
export { txtSaveFormatDefinition };
export type { ChatMessage };
export type { ChatParticipant };
export type { MessageButton };
export { parseMessageButtons };
export { ArrowIcon };
export { AttachmentIcon };
export { MicIcon };
export { PauseIcon };
export { PlayIcon };
export { ResetIcon };
export { SaveIcon };
export { SendIcon };
export { TemplateIcon };
export { PromptbookAgent };
export { BrandedQrCode };
export { GenericQrCode };
export { PromptbookQrCode };
export { injectCssModuleIntoShadowRoot };
export { AboutPromptbookInformation };
