// ⚠️ WARNING: This code has been generated so that any manual changes will be overwritten
// `@promptbook/markdown-utils`

import { extractBlock } from '../postprocessing/utils/extractBlock';
import { extractJsonBlock } from '../postprocessing/utils/extractJsonBlock';
import { createMarkdownScraper } from '../scrapers/markdown/createMarkdownScraper';
import { MarkdownScraper } from '../scrapers/markdown/MarkdownScraper';
import { _MarkdownScraperRegistration } from '../scrapers/markdown/register-constructor';
import type {
    string_markdown,
    string_markdown_codeblock_language,
    string_markdown_section,
    string_markdown_section_content,
    string_markdown_text,
} from '../types/typeAliases';
import { addAutoGeneratedSection } from '../utils/markdown/addAutoGeneratedSection';
import { createMarkdownChart } from '../utils/markdown/createMarkdownChart';
import { createMarkdownTable } from '../utils/markdown/createMarkdownTable';
import { escapeMarkdownBlock } from '../utils/markdown/escapeMarkdownBlock';
import { extractAllBlocksFromMarkdown } from '../utils/markdown/extractAllBlocksFromMarkdown';
import { extractAllListItemsFromMarkdown } from '../utils/markdown/extractAllListItemsFromMarkdown';
import { extractOneBlockFromMarkdown } from '../utils/markdown/extractOneBlockFromMarkdown';
import { flattenMarkdown } from '../utils/markdown/flattenMarkdown';
import type { MarkdownSection } from '../utils/markdown/parseMarkdownSection';
import { parseMarkdownSection } from '../utils/markdown/parseMarkdownSection';
import { removeMarkdownComments } from '../utils/markdown/removeMarkdownComments';
import { removeMarkdownFormatting } from '../utils/markdown/removeMarkdownFormatting';
import { splitMarkdownIntoSections } from '../utils/markdown/splitMarkdownIntoSections';
import { BOOK_LANGUAGE_VERSION, PROMPTBOOK_ENGINE_VERSION } from '../version';

// Note: Exporting version from each package
export { BOOK_LANGUAGE_VERSION, PROMPTBOOK_ENGINE_VERSION };

// Note: Entities of the `@promptbook/markdown-utils`
export {
    _MarkdownScraperRegistration,
    addAutoGeneratedSection,
    createMarkdownChart,
    createMarkdownScraper,
    createMarkdownTable,
    escapeMarkdownBlock,
    extractAllBlocksFromMarkdown,
    extractAllListItemsFromMarkdown,
    extractBlock,
    extractJsonBlock,
    extractOneBlockFromMarkdown,
    flattenMarkdown,
    MarkdownScraper,
    parseMarkdownSection,
    removeMarkdownComments,
    removeMarkdownFormatting,
    splitMarkdownIntoSections,
};
export type {
    MarkdownSection,
    string_markdown,
    string_markdown_codeblock_language,
    string_markdown_section,
    string_markdown_section_content,
    string_markdown_text,
};
