import type { ChatMessage } from '../../../../../../src/book-components/Chat/types/ChatMessage';

export const longThreadScenario = {
    name: 'Looooooong Thread',
    messages: [
        {
            id: '1',
            createdAt: new Date(),
            sender: 'USER',
            content: 'Hey, has anyone heard of this thing called Promptbook? 🤔',
            isComplete: true,
        },
        {
            id: '2',
            createdAt: new Date(),
            sender: 'ASSISTANT_1',
            content:
                "Oh yeah! It's like a cookbook, but instead of recipes for food, it has recipes for AI prompts! 👨‍🍳✨",
            isComplete: true,
        },
        {
            id: '3',
            createdAt: new Date(),
            sender: 'USER',
            content: 'Wait, so I can make my AI "cook" better responses? 🍳',
            isComplete: true,
        },
        {
            id: '4',
            createdAt: new Date(),
            sender: 'ASSISTANT_2',
            content: 'Exactly! And the best part? No burned prompts in the kitchen! 🔥😅',
            isComplete: true,
        },
        {
            id: '5',
            createdAt: new Date(),
            sender: 'ASSISTANT_1',
            content:
                'Plus you can version control your recipes. "Git commit -m \'Added more salt to the prompt\'" 🧂💻',
            isComplete: true,
        },
        {
            id: '6',
            createdAt: new Date(),
            sender: 'USER',
            content: 'Does it come with a prompt sous chef? 👨‍🍳',
            isComplete: true,
        },
        {
            id: '7',
            createdAt: new Date(),
            sender: 'ASSISTANT_3',
            content: 'It\'s called "pipeline execution" - your personal AI kitchen staff! 🏭👥',
            isComplete: true,
        },
        {
            id: '8',
            createdAt: new Date(),
            sender: 'ASSISTANT_2',
            content:
                'And if something goes wrong, you get proper error messages instead of just "prompt machine broke" 🤖💔',
            isComplete: true,
        },
        {
            id: '9',
            createdAt: new Date(),
            sender: 'USER',
            content: 'Can I share my prompt recipes with friends? 🤝',
            isComplete: true,
        },
        {
            id: '10',
            createdAt: new Date(),
            sender: 'ASSISTANT_1',
            content:
                "Of course! It's open source - like a community cookbook where everyone adds their secret ingredients! 📚🌟",
            isComplete: true,
        },
        {
            id: '11',
            createdAt: new Date(),
            sender: 'ASSISTANT_3',
            content:
                'Speaking of ingredients, have you tried the "expectation" parameter? It\'s like seasoning for your outputs! 🧄',
            isComplete: true,
        },
        {
            id: '12',
            createdAt: new Date(),
            sender: 'USER',
            content: 'Expectation parameter? Tell me more! 👀',
            isComplete: true,
        },
        {
            id: '13',
            createdAt: new Date(),
            sender: 'ASSISTANT_2',
            content:
                'It\'s like telling the AI "I expect this to be formatted as JSON" or "I expect a poem" - no more surprise ingredients! 🎭',
            isComplete: true,
        },
        {
            id: '14',
            createdAt: new Date(),
            sender: 'ASSISTANT_1',
            content:
                "And the scripting language? It's like having measurement cups for prompts - precise and reproducible! 📏⚖️",
            isComplete: true,
        },
        {
            id: '15',
            createdAt: new Date(),
            sender: 'USER',
            content: "This sounds too good to be true. What's the catch? 🎣",
            isComplete: true,
        },
        {
            id: '16',
            createdAt: new Date(),
            sender: 'ASSISTANT_3',
            content: 'The only catch is you might become addicted to well-structured prompts! ⚡🧠',
            isComplete: true,
        },
        {
            id: '17',
            createdAt: new Date(),
            sender: 'ASSISTANT_2',
            content: 'And you\'ll start judging other people\'s prompts like Gordon Ramsay: "This prompt is RAW!" 😤👨‍🍳',
            isComplete: true,
        },
        {
            id: '18',
            createdAt: new Date(),
            sender: 'USER',
            content: 'LOL! Does it work with different AI models? 🤖',
            isComplete: true,
        },
        {
            id: '19',
            createdAt: new Date(),
            sender: 'ASSISTANT_1',
            content:
                "It's like a universal adapter - works with OpenAI, Anthropic, Azure... it's promiscuous with models! 🔌✨",
            isComplete: true,
        },
        {
            id: '20',
            createdAt: new Date(),
            sender: 'ASSISTANT_3',
            content: "Just don't tell one model about the others... we don't want jealous AIs! 💔🤖",
            isComplete: true,
        },
        {
            id: '21',
            createdAt: new Date(),
            sender: 'USER',
            content: 'Can I use it in production? 🏭',
            isComplete: true,
        },
        {
            id: '22',
            createdAt: new Date(),
            sender: 'ASSISTANT_2',
            content: 'Absolutely! It even has enterprise features - because corporate prompts need suits too! 👔💼',
            isComplete: true,
        },
        {
            id: '23',
            createdAt: new Date(),
            sender: 'ASSISTANT_1',
            content:
                'And monitoring dashboards! Finally, you can watch your prompts work like a helicopter parent! 🚁📊',
            isComplete: true,
        },
        {
            id: '24',
            createdAt: new Date(),
            sender: 'USER',
            content: 'What about debugging? I hate cryptic AI errors... 🐛',
            isComplete: true,
        },
        {
            id: '25',
            createdAt: new Date(),
            sender: 'ASSISTANT_3',
            content: 'Promptbook gives you actual stack traces! No more "AI said no" error messages! 🔍📋',
            isComplete: true,
        },
        {
            id: '26',
            createdAt: new Date(),
            sender: 'ASSISTANT_2',
            content: 'It\'s like having a translator for AI moods: "The model is feeling picky about JSON today" 🌡️🤖',
            isComplete: true,
        },
        {
            id: '27',
            createdAt: new Date(),
            sender: 'USER',
            content: 'This conversation has convinced me. Where do I start? 🚀',
            isComplete: true,
        },
        {
            id: '28',
            createdAt: new Date(),
            sender: 'ASSISTANT_1',
            content:
                'GitHub: github.com/webgptorg/promptbook - but warning: you might lose sleep reading the docs! 📖🌙',
            isComplete: true,
        },
        {
            id: '29',
            createdAt: new Date(),
            sender: 'ASSISTANT_3',
            content:
                'And join the community! We have cookies... well, metaphorical ones. And great prompt recipes! 🍪👥',
            isComplete: true,
        },
        {
            id: '30',
            createdAt: new Date(),
            sender: 'ASSISTANT_2',
            content: 'Fair warning: once you go Promptbook, you never go back to spaghetti prompts! 🍝➡️📚',
            isComplete: true,
        },
        {
            id: '31',
            createdAt: new Date(),
            sender: 'USER',
            content: 'Spaghetti prompts? 😂',
            isComplete: true,
        },
        {
            id: '32',
            createdAt: new Date(),
            sender: 'ASSISTANT_1',
            content:
                "You know, those tangled, messy prompts with no structure... like mom's spaghetti, but for AI! 🍝😵‍💫",
            isComplete: true,
        },
        {
            id: '33',
            createdAt: new Date(),
            sender: 'ASSISTANT_3',
            content: 'Promptbook turns your spaghetti into a beautiful, organized bento box! 🍱✨',
            isComplete: true,
        },
        {
            id: '34',
            createdAt: new Date(),
            sender: 'USER',
            content: "I'm getting hungry now... and excited about structured prompts! 🍽️🎉",
            isComplete: true,
        },
        {
            id: '35',
            createdAt: new Date(),
            sender: 'ASSISTANT_2',
            content: 'Perfect combo! Grab a snack and start coding - the best way to learn Promptbook! 🥪💻',
            isComplete: true,
        },
        {
            id: '36',
            createdAt: new Date(),
            sender: 'ASSISTANT_1',
            content: 'And remember: with great prompting power comes great responsibility! 🕷️⚡',
            isComplete: true,
        },
        {
            id: '37',
            createdAt: new Date(),
            sender: 'USER',
            content: 'Uncle Ben would be proud... if he knew what AI prompting was! 👴💭',
            isComplete: true,
        },
        {
            id: '38',
            createdAt: new Date(),
            sender: 'ASSISTANT_3',
            content: '"With great prompting comes great debugging"... wait, that doesn\'t sound as inspiring! 🐞😅',
            isComplete: true,
        },
        {
            id: '39',
            createdAt: new Date(),
            sender: 'ASSISTANT_2',
            content: 'How about: "With great Promptbook comes great productivity!" Much better! 📈🚀',
            isComplete: true,
        },
        {
            id: '40',
            createdAt: new Date(),
            sender: 'USER',
            content: 'I can see why this thread got so long... Promptbook is addictive to talk about! 🗣️💉',
            isComplete: true,
        },
        {
            id: '41',
            createdAt: new Date(),
            sender: 'ASSISTANT_1',
            content: "Just wait until you start using it - you'll be evangelizing to everyone at coffee shops! ☕🗣️",
            isComplete: true,
        },
        {
            id: '42',
            createdAt: new Date(),
            sender: 'ASSISTANT_3',
            content: '"Excuse me, but have you heard about our lord and savior, Structured Prompting?" ⛪📚',
            isComplete: true,
        },
        {
            id: '43',
            createdAt: new Date(),
            sender: 'USER',
            content: 'LMAO! I can already see myself doing that! 😂🙋‍♂️',
            isComplete: true,
        },
        {
            id: '44',
            createdAt: new Date(),
            sender: 'ASSISTANT_2',
            content: 'Welcome to the cult... I mean, community of organized prompt enthusiasts! 🎭👥',
            isComplete: true,
        },
        {
            id: '45',
            createdAt: new Date(),
            sender: 'ASSISTANT_1',
            content: 'We have t-shirts: "I ❤️ Promptbook" and "Ask me about my execution pipelines!" 👕❤️',
            isComplete: true,
        },
        {
            id: '46',
            createdAt: new Date(),
            sender: 'USER',
            content: "Okay, I'm definitely convinced now. Time to go play with some prompts! 🎮📝",
            isComplete: true,
        },
        {
            id: '47',
            createdAt: new Date(),
            sender: 'ASSISTANT_3',
            content: 'Happy prompting! May your expectations always be met and your outputs never be undefined! 🙏✨',
            isComplete: true,
        },
        {
            id: '48',
            createdAt: new Date(),
            sender: 'ASSISTANT_2',
            content: 'And may your pipelines always execute without errors! Amen! 🛠️🙏',
            isComplete: true,
        },
        {
            id: '49',
            createdAt: new Date(),
            sender: 'ASSISTANT_1',
            content: 'This has been the most wholesome AI tool discussion ever. Group hug! 🤗👥',
            isComplete: true,
        },
        {
            id: '50',
            createdAt: new Date(),
            sender: 'USER',
            content: 'Virtual group hug! Thanks everyone - see you in the Promptbook community! 🤗👋',
            isComplete: true,
        },
    ] as ChatMessage[],
};
