name: Tests - Test Package generation

on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main

jobs:
    test-package-generation:
        name: 🧪 Test Package generation
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-node@v4
              with:
                  node-version: 22

            - name: Install dependencies
              run: npm ci

            - name: Test Package generation
              run: npm run test-package-generation
